### ISSUE TITLE
Email classification dataset

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#100]
I would like to add an email classification dataset to `creme`. A couple months ago @gbolmier and I had a look online but weren't really satisfied by what was available. If someone has a suggestion feel free to propose.

**Comment by duttashi** [comment]
@MaxHalford, it is unclear from the issue to what you have seen online. Have you checked the [Enron email dataset](https://www.cs.cmu.edu/~./enron/enron_mail_20150507.tar.gz), [Enron email dataset from Kaggle](https://www.kaggle.com/wcukierski/enron-email-dataset) and the classic [Spambase](https://archive.ics.uci.edu/ml/datasets/Spambase) dataset from UCI ML repository?

A project to label a subset of this email corpus can be found on this [UC Berkley site](http://bailando.sims.berkeley.edu/enron_email.html).

**Comment by gbolmier** [comment]
Hi @duttashi! Thx for the ressources you pointed out :relaxed:

Indeed we had a look at Enron and Spambase datasets. Unfortunately, the first one is quite a mess and lacks of structure, the second one is quite small (4601 obs) and doesn't represent well a real life spam problem (39.4% of spam). 

We would prefer a large structured dataset approved by the community, it would make things easier to assess performance and comparisons... at the end maybe we should just get our hands dirty with the Enron one but I don't want to build our own dataset from it, there must be a standard to compare 
people's work. Maybe we didn't look hard enough, would love to get feedback from someone of the field!

What are your opinion folks?

**Comment by gbolmier** [comment]
After more investigations I found two interesting datasets:
- **sms spam collection**: 5,574 sms with 13.4% tagged as spam. Only one feature, the sms text, clean and directly usable. [UCI repository](https://archive.ics.uci.edu/ml/datasets/sms+spam+collection), [paper](http://www.dt.fee.unicamp.br/~tiago/smsspamcollection/doceng11.pdf).
- **trec07p**: 75,419 emails with 66.6% tagged as spam. Large dataset but quite a mess... parsing and data cleaning/pre-processing need to be done before being usable. In a first time I just parsed data to get the following fields ([code](https://gist.github.com/gbolmier/b6a942699aaaedec54041a32e4f34d40)):
  - sender
  - recipients
  - date
  - subject
  - body

  Even if it belongs to data scientists, we should maybe propose a basic data cleaning/pre-processing in option. Any opinions? [trec07p repository](https://plg.uwaterloo.ca/~gvcormac/treccorpus07/), [paper](https://trec.nist.gov/pubs/trec16/papers/SPAM.OVERVIEW16.pdf)

I just submitted a pull request to make those 2 datasets available :tada:

**Comment by MaxHalford** [comment]
Good job!
