### ISSUE TITLE
Decision tree improvements

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#104]
Online decision trees are working but there is some work to make them really efficient and usable in practice. This issue will keep track of the work that is being done on them.

- [ ] Support regression (at the moment we only do binary and multi classification)
- [ ] Skewed split prevention as explained in section 3.2.6 of [this wonderful book](https://www.cs.waikato.ac.nz/~abifet/MOA/StreamMining.pdf)
- [x] Use Gini index for splitting
- [ ] Streaming quantiles/percentiles for discretising continuous values

**Comment by AdilZouitine** [comment]
I tried the Gini index proposed in this [paper](https://arxiv.org/pdf/1403.6348.pdf) but I didn't get the right results!

After the AUC I would re-examine this calculation.
