### ISSUE TITLE
Equi-height histograms

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#105]
Thanks to @AdilZouitine we now have histograms whose bins follow quantiles. It would be really nice if we could also have equi-height histograms, where only the width of the bins changes. This would extremely useful for online decision trees.

**Comment by AdilZouitine** [comment]
I think we can use the algorithm of the histogram in `utils` to make this task work.

**Comment by MaxHalford** [comment]
Sure but I'm not sure how to do this efficiently each time `update` is called.

**Comment by MaxHalford** [comment]
Turns out this isn't needed. My bad.
