### ISSUE TITLE
Pipeline drawing edge-case

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#106]
I just found a case where the `Pipeline.draw` method fails:

```python
from creme import compose
from creme import datasets
from creme import feature_extraction
from creme import linear_model
from creme import preprocessing
from creme import stats


X_y = datasets.fetch_bikes()

def add_hour(x):
    return {
        **x,
        'hour': x['moment'].hour
    }

model = compose.Whitelister('clouds', 'humidity', 'pressure', 'temperature', 'wind')
model += (
    add_hour | (
        feature_extraction.TargetAgg(by=['station', 'hour'], how=stats.Mean()) +
        feature_extraction.TargetAgg(by='station', how=stats.EWMean())
    )
)
model |= preprocessing.StandardScaler()
model |= linear_model.LinearRegression()

model.draw()
```

This is what I get:

![Digraph gv](https://user-images.githubusercontent.com/8095957/58383340-c61c0f00-7fd5-11e9-809f-96616bd0fce7.png)

But it should be something like this:

![Untitled drawing](https://user-images.githubusercontent.com/8095957/58383413-afc28300-7fd6-11e9-8756-5186005a42bc.png)

I think we have some brainstorming to do @gbolmier :)

**Comment by gbolmier** [comment]
Aïe :sweat_smile: thx @MaxHalford!

**Comment by gbolmier** [comment]
Fixed sir! I just submitted the PR :wink:

My bad, it was a little oversight... but I think there is still things we need to discuss together (e.g. estimators declarative order isn't respected here, in your example we first declare our model with a `Whitelister` but it ends up in second position, right after the `Pipeline` starting with the `add_hour` func)

**Comment by MaxHalford** [comment]
Nice one!

I think that if you sort the keys you loop over for the `TransformerUnion` then it should work. What I mean is replace `for ix, sub_key in enumerate(step.keys())` with `for ix, sub_key in enumerate(sorted(step.keys()))`. If you have the time can you check if it works and update your PR? :)

**Comment by gbolmier** [comment]
Actually there is no need for `ix` and `enumerate` now! I'm updating it

**Comment by MaxHalford** [comment]
Thanks!
