### ISSUE TITLE
Naive KNN implementation

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#109]
KNN seem to be difficult to do online, mostly because there doesn't seem to be any reliable and simple way to add to and delete from a nearest neighbors data structure. However, there is good reason to believe that KNNs are good for online learning because they naturally adapt to drift. 

What we can do is start with a naive implementation where we maintain a list of the `n` most recent observations (using `utils.Window`). We can then simply loop through the window for making predictions by comparing each of the window's observations distance with the observation that is being predicted. This shouldn't be too hard to do. If possible it would be nice to cover all the options that [sklearn has](https://scikit-learn.org/stable/modules/neighbors.html).

This is a really good first issue for someone who wants to get started. Feel free to ask for questions.

**Comment by MaxHalford** [comment]
Sure, have a go! Don't hesitate to ask questions if you have any doubts :)

**Comment by jklaise** [comment]
For inspiration, there is an implementation of this in [scikit-multiflow](https://scikit-multiflow.github.io/scikit-multiflow/_autosummary/skmultiflow.lazy.KNN.html#skmultiflow.lazy.KNN). @MaxHalford I'm interest more generally if there is overlap with `creme` and `skmultiflow`, e.g. are concept drift algorithms on the roadmap?

**Comment by MaxHalford** [comment]
There will be definitely some overlap between `creme` and `skmultiflow`, at least from an algorithmic point of view. Concept drift is definitely something we want to do.

**Comment by MaxHalford** [comment]
Any progress @Raul9595? :)

**Comment by Raul9595** [comment]
I'm sorry. Have been really busy the past few weeks. Will take it up from today.

**Comment by MaxHalford** [comment]
No pressure :)

**Comment by Raul9595** [comment]
Theres one question I had. under which module do you want me to add this implementation?

**Comment by MaxHalford** [comment]
Good question; it should be under a new module called `neighbours`.

**Comment by MaxHalford** [comment]
Done! See the new `neighbors` module.
