### ISSUE TITLE
Document features with unit tests

### ISSUE THREAD

**Issue by flegac** [creme-ml/creme#112]
Just an idea : document your code with unit tests (maybe give a try at TDD methodology ?).
A good start would be to write a unit test for each supported model.

This will both :
- document your project with little maintenance overhead
- demonstrate the quality of your library

Given your pretention (production ready), you need at least good test coverage.

PS: Some comments are nearly unit test (usage demonstration), just move that code from comments to their own file in "tests" folder !

**Comment by MaxHalford** [comment]
The documentation of each class actually serves as unit tests. This is done with a Python tool called [doctest](https://pymotw.com/3/doctest/). This way the examples show up in the documentation, and will also be check by pytest. 

If you look at the README it says that test coverage is of 89%, so don't worry.
