### ISSUE TITLE
Expose benchmarks

### ISSUE THREAD

**Issue by flegac** [creme-ml/creme#113]
During your Online training talk you compare Creame to Scikit-learn in terms of speed.
Please keep a place in "tests" folder for some benchmarking scripts (you seem to have them in some place anyway).

**Comment by MaxHalford** [comment]
There is an exposed benchmark; see [here](https://creme-ml.github.io/notebooks/electricity.html).

**Comment by flegac** [comment]
Right ! I did see it, but miss the timings !

**Comment by MaxHalford** [comment]
But you're right, there's still a lot to do :). I think that having a table with benchmarks in the README would be nice. A bit like [what surprise does](https://github.com/NicolasHug/Surprise#benchmarks).
