### ISSUE TITLE
Stream joins

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#117]
I think it would be worthwhile to include a utility for joining two (or more?) streams of data. See [this example](https://databricks.com/blog/2018/03/13/introducing-stream-stream-joins-in-apache-spark-2-3.html).

**Comment by AdilZouitine** [comment]
Next week I can work on it.

**Comment by MaxHalford** [comment]
With hindsight it seems that this is outside `creme`'s scope, and we will thus not pursue for the while.
