### ISSUE TITLE
WoW dataset

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#119]
I would like to add the World of Warcraft logs dataset described [here](https://www.iis.sinica.edu.tw/~swc/pub/world_of_warcraft_avatar_history.html). The data needs a bit of preprocessing before it can be ingested by `creme`. Once this is done we can add it to `datasets` module.

**Comment by hemanthsavasere** [comment]
Hi @MaxHalford,
If anyone is not working, I want to work on this issue, can I have a go ?

**Comment by MaxHalford** [comment]
Sure! :)

**Comment by MaxHalford** [comment]
Any news on this @hemanthsavasere?
