### ISSUE TITLE
Contributing a tutorial on using Creme for image classification.

### ISSUE THREAD

**Issue by jrosebr1** [creme-ml/creme#122]
Hello Creme maintainers!

My name is Adrian Rosebrock, I run a popular computer vision and deep learning blog called PyImageSearch.com. I'm not here to post a bug report, but I wanted to share a tutorial I just published on using:

1. Keras for deep learning-based (image) feature extraction
2. Using Creme to train a Logistic Regression classifier on top of the features

The guide itself can before found here:

https://www.pyimagesearch.com/2019/06/17/online-incremental-learning-with-keras-and-creme/

Using the tutorial readers can easily work with a dataset too large to fit into memory.

I really enjoyed using Creme to create the guide and just wanted to reach out and show my thanks for building such a great library. I wish you all the best with it!

If you think it's appropriate please do feel free to reference the guide as an example of using Creme -- I hope it helps your users (and takes some support load off your shoulders).

**Comment by raphaelsty** [comment]
Nice demonstration

**Comment by AdilZouitine** [comment]
Great ! :smile:

**Comment by MaxHalford** [comment]
Hello Adrian! I remember reading of few of your blog posts with great interest. Thank you for this, it's really great, and makes me really happy. We'll be adding your blog post to the [Useful links](https://github.com/creme-ml/creme#useful-links) section of the README.

Again, very nice work.

**Comment by MaxHalford** [comment]
@jrosebr1 I also added you to the list of contributors.

**Comment by jrosebr1** [comment]
Thanks @MaxHalford! 😄
