### ISSUE TITLE
`math.dot` is not commutative

### ISSUE THREAD

**Issue by Adam-Hoelscher** [creme-ml/creme#127]
Docstring for the function `dot` from `creme.utils.math`: Returns the dot product of two vectors represented as dicts.

The function actually returns the product of the shorter of the two vectors and the second vector. i.e. if the second vector is shorter, it is multiplied by itself rather than by the first. This make the function not commutative, but a dot product is commutative.

Recreation
```
a = {'x' + str(i): i for i in range(5)}
b = {'x' + str(i): i + 1 for i in range(3)}
dp1 = dot(x=a, y=b)
dp2 = dot(x=b, y=a)
assert dp1==dp2
```

I'm writing a fix for this and I'll put in a pull request in the next couple days.

**Comment by MaxHalford** [comment]
Good catch... I'm ashamed!

**Comment by MaxHalford** [comment]
Fixed.
