### ISSUE TITLE
Gradient boosting

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#13]
There seem to be a lot of possible implementations, as can be seen by [a quick Google search](https://www.google.com/search?q=online+gradient+boosting&ie=utf-8&oe=utf-8&client=firefox-b-ab).

**Comment by ryan102590** [comment]
Hey Max, interesting work so far! What do you think of leaving the type of regressor open when doing the gradient boosting? Looking at what you have so far it would be interesting to see if a gradient boosted mondrian trees regressor could be implement?

**Comment by MaxHalford** [comment]
Hey @ryan102590,

Yeah for sure, the regressor will be provided on the user's side. I did that for a recent project of mine called [starboost](https://maxhalford.github.io/starboost/).

**Comment by ryan102590** [comment]
@MaxHalford 

Very nice! Did you implement a partial_fit for that version as well?

**Comment by MaxHalford** [comment]
Nope `starboost` is purely focused on batch learning!

**Comment by AdilZouitine** [comment]
Some interesting papers:
- [Online Gradient Boosting](https://arxiv.org/pdf/1506.04820.pdf) 
- [Online Baggind and Boosting](https://ti.arc.nasa.gov/m/profile/oza/files/ozru01a.pdf) 
- [Optimal and Adaptive Algorithms for Online Boosting](http://proceedings.mlr.press/v37/beygelzimer15.pdf)

**Comment by MaxHalford** [comment]
See [this](https://github.com/benedekrozemberczki/awesome-gradient-boosting-papers) repo too.

**Comment by MaxHalford** [comment]
I just merge `ensemble.AdaBoostClassifier`, cheers @raphaelsty! Now it would be nice if we could implement other boosting methods and compare them.
