### ISSUE TITLE
Scaler in debug_one returning nan

### ISSUE THREAD

**Issue by konradsitarz** [creme-ml/creme#130]
I bumped into the issue when I tried to use Pipeline debug_one method. Scaler wasn't fitting the data using the fit_one method before transforming and the result was dict with all nan values.
```
0. Input
--------
STARTDATETIME: 2018-09-21 22:00:00 (Timestamp)
HUMIDITY: 68.59412222222221 (float)
PM10: 37.111111111111114 (float)
PM25: 32.111111111111114 (float)
TEMPERATURE: 19.59688888888889 (float)

1. ['HUMIDITY', 'PM10', 'PM25', 'TEMPERATURE']
----------------------------------------------
PM10: 37.111111111111114 (float)
HUMIDITY: 68.59412222222221 (float)
PM25: 32.111111111111114 (float)
TEMPERATURE: 19.59688888888889 (float)

2. MinMaxScaler
---------------
PM10: nan (float)
HUMIDITY: nan (float)
PM25: nan (float)
TEMPERATURE: nan (float)

3. LinearRegression
-------------------
0.0 * nan (PM10) +
0.0 * nan (HUMIDITY) +
0.0 * nan (PM25) +
0.0 * nan (TEMPERATURE)

nan
```

I changed slightly the implementation of debug_one in Pipeline class. I added call to fit_one if transformer has this method.
```

        for i, t in enumerate(self.transformers):
           # my change
            if callable(getattr(t, 'fit_one', None)):
                t.fit_one(x)
           # ----
            if isinstance(t, union.TransformerUnion):
                print_title(f'{i+1}. Transformer union')
                for j, (name, sub_t) in enumerate(t.items()):
                    print_title(f'{i+1}.{j} {name}', indent=True)
                    print_features(sub_t.transform_one(x), indent=True)
                x = t.transform_one(x)
                print_features(x)
            else:
                print_title(f'{i+1}. {t}')
                x = t.transform_one(x)
                print_features(x)
```

With this change I was able to see values of scaled parameters.
At the end I would like to thank you for very interesting project. I hope it will raise to be commonly used in incremental learning. Cheers :)

**Comment by MaxHalford** [comment]
Hey, thank you for the kind words!

What you've stumbled on is not bug, it's a feature. In a pipeline, the `fit_one` method of each transformer is called in the `predict_one` method of the pipeline, not in the `fit_one` method. This may seem confusing at first, but if you think about it's better to allow the transformers to be updated as early as possible. To fix your issue, you have to call the `predict_one` method of the pipeline before calling `fit_one`.

Feel free to tell me if I wasn't clear.

**Comment by konradsitarz** [comment]
Ok, so before trying to debug should I call predict firstly as in example bellow?

```
x, y = next(X_y)
model.predict_one(x)
model.debug_one(x)
```

**Comment by MaxHalford** [comment]
Exactly. 

A pattern I advise is as follows:

```python
for i, (x, y) in enumerate(X_y):
    y_pred = model.predict_one(x)

    if i == 1000:
        model.debug_one(x)
        break

    model.fit_one(x)
```
