### ISSUE TITLE
What about Numenta's hierarchical temporal memory?

### ISSUE THREAD

**Issue by nbro** [creme-ml/creme#131]
Wouldn't it be useful to also include HTM's temporal memory and spatial pooler in this package? They are particularly suited for online learning in an unsupervised fashion. Would there be any license-related issues? I think you should ask them directly.

**Comment by MaxHalford** [comment]
Hey! I know nothing about this, I'll look into it. Thanks for opening the issue.

**Comment by MaxHalford** [comment]
Looks way too mysterious, also there seems to be licensing issues.
