### ISSUE TITLE
Incremental Gaussian Processes

### ISSUE THREAD

**Issue by abonte** [creme-ml/creme#137]
Resource:

[Efficient Multi-Class Incremental Learning Using Gaussian Processes](https://pub.inf-cv.uni-jena.de/pdf/Luetz13:IWT.pdf)

I would like to work on this if it is ok.

**Comment by raphaelsty** [comment]
Hi @abonte, for sure, don't hesitate to work on it :-)

**Comment by MaxHalford** [comment]
See [Gaussian Processes for Big Data](https://arxiv.org/abs/1309.6835) too.
