### ISSUE TITLE
Using Creme model in Python 2

### ISSUE THREAD

**Issue by aamirkhan34** [creme-ml/creme#138]
Hi Guys,

Suppose, I trained a logistic-regression classifier using Python 3.x as Creme only supports Python 3. How can I use the model for classification in Python 2?

**Comment by MaxHalford** [comment]
Hey,

Python 2 isn't supported, and never will be. It would just be too much additional work for us.

**Comment by aamirkhan34** [comment]
Hi @MaxHalford,

Thanks for a prompt response. 
Can I convert the trained model to sklearn format and then use it using Python 2?

Thanks.

**Comment by MaxHalford** [comment]
I suppose you could! Just curious, are you using Python 2 at work?

**Comment by aamirkhan34** [comment]
Yes, we are using Python 2 for our project. We have been working on this project since 2017.
How can we convert a trained model to sklearn format?

**Comment by MaxHalford** [comment]
Take a look at the `convert_creme_to_sklearn` method from the `compat` module.

**Comment by aamirkhan34** [comment]
I converted the model using convert_creme_to_sklearn. However, which I try to predict using model.predict(), it gives the following error:
NotFittedError: This SKLTransformerWrapper instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

**Comment by MaxHalford** [comment]
Hey, can you try and set the `is_fitted_` parameter of the wrapped model to `True`? This is a quirk of wrapping the model and not calling `fit` afterwards.

**Comment by aamirkhan34** [comment]
I did the following:
creme_classifier = pickle.load(open(creme_model_path, 'rb'))
sklearn_classifier = convert_creme_to_sklearn(creme_classifier)
sklearn_classifier.is_fitted_ = True
print(sklearn_classifier.is_fitted_)
    
# Save Model
filename = 'sklearn_model.pkl'
pickle.dump(sklearn_classifier, open(filename, 'wb'))

**When I load the model, I still get the same error:** 
NotFittedError: This SKLTransformerWrapper instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

**My Creme model Pipeline:** 
creme_model = Pipeline([
    ("scale", MinMaxScaler()),
    ("fet_sel", feature_selection.SelectKBest(similarity=stats.PearsonCorrelation(), k=2500)),
    ("learn", OneVsRestClassifier(
        binary_classifier=LogisticRegression()))
])

**Comment by MaxHalford** [comment]
Okay, try the following:

```python
sklearn_classifier[0].is_fitted_ = True
sklearn_classifier[1].is_fitted_ = True
sklearn_classifier[2].classes_ = ['class_1', 'class_2', 'class_3']
```

You could also copy/paste the code from [`compat/sklearn`](https://github.com/creme-ml/creme/blob/master/creme/compat/sklearn.py) and remove the `utils.validation.check_is_fitted` method from `SKLClassifierWrapper`'s `predict` method.

**Comment by aamirkhan34** [comment]
Thanks @MaxHalford. I tried both the approaches that you mentioned. The second one where I commented the utils.validation.check_is_fitted line gave the same error.

In the first approach: 
I added:
sklearn_classifier[0].is_fitted_ = True
sklearn_classifier[1].is_fitted_ = True

However, didn't give the same error. I believed that's fixed. Now it gave the following error:
~/anaconda3/envs/tflow/lib/python3.6/site-packages/creme/compat/sklearn.py in transform(self, X)
--> 527         if X.shape[1] != self.n_features_:
    528             raise ValueError(f'Expected {self.n_features_} features, got {X.shape[1]}')
    529 

AttributeError: 'SKLTransformerWrapper' object has no attribute 'n_features_'

**Comment by MaxHalford** [comment]
Sorry but it's really hard to debug without some more code. I'm going to need a full example of what you're trying to do.

**Comment by aamirkhan34** [comment]
Sure. Here's the complete snippet:

My current Creme model Pipeline:
creme_model = Pipeline([
("learn", OneVsRestClassifier(
binary_classifier=PAClassifier()))
])

I am using Keras VGG16 for feature extraction the features in a CSV.

Then I am iterating through the CSV and training the above Pipeline like below:
metric = Accuracy()

# loop over the dataset
for (i, (X, y)) in enumerate(dataset):
      # make predictions on the current set of features, train the
      # model on the features, and then update our metric
      preds = creme_model.predict_one(X)
      creme_model = creme_model.fit_one(X, y)
      metric = metric.update(y, preds)
      print("INFO] update {} - {}".format(i, metric))

# show the accuracy of the model
print("\n[INFO] final - {}".format(metric))

- Then I save the model using Pickle
- After saving, I transform the model for Sklearn using the following code:

creme_classifier = pickle.load(open(creme_model_path, 'rb'))
sklearn_classifier = convert_creme_to_sklearn(creme_classifier)
sklearn_classifier[0].is_fitted_ = True
# Save Model
pickle.dump(sklearn_classifier, open(output_path, 'wb'))

- Sklearn model is created. Now comes the problem:
When I load the sklearn model and try to predict using the following code:
preds = loaded_model.predict(image_features)

It throws the following error:
**NotFittedError: This SKLClassifierWrapper instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.**

Please let me know if you need additional details

**Comment by MaxHalford** [comment]
Just so you know, you can format code using 3 back ticks; it helps a lot.

What you need to do is this:

```python
sklearn_classifier[0].classes_ = list(sklearn_classifier.creme_estimator.keys())
```

I didn't run your code but this should work.

**Comment by aamirkhan34** [comment]
Thanks @MaxHalford . I updated the code, converted the model:
When I am trying to predict I am getting the following error:

AttributeError: 'SKLClassifierWrapper' object has no attribute 'n_features_'

**Comment by MaxHalford** [comment]
Okay so what if you do the following?

```python
sklearn_classifier[0].classes_ = list(sklearn_classifier.creme_estimator.keys())
sklearn_classifier[0].n_features_ = 6  # The number depends on your dataset
```

Sorry if things are hacky, `SKLClassifierWrapper` wasn't meant to do this in the first place. It's simply here to be able to use a `creme` within `sklearn`'s API.

**Comment by aamirkhan34** [comment]
@MaxHalford No worries. This library is very helpful and solves one of the most challenging problems in Machine Leaning. Really appreciate the team's effort.

I did as you said and I ran into the following error:
**AttributeError: 'SKLClassifierWrapper' object has no attribute 'instance_'**

**Comment by MaxHalford** [comment]
Okay now this should work (famous last words):

```python
sklearn_classifier[0].classes_ = list(sklearn_classifier.creme_estimator.keys())
sklearn_classifier[0].n_features_ = 6  # The number depends on your dataset
sklearn_classifier[0].instance_ = sklearn_classifier.creme_estimator
```

**Comment by aamirkhan34** [comment]
I did this and I didn't get any other error. However, my sk-learn model predicts the same label for all the inputs. The probabilities are almost same for all the labels. I get the right prediction when I use the corresponding creme model.

**Comment by MaxHalford** [comment]
I have no idea... I'm going to a **full** script in order to see what's going on.

**Comment by aamirkhan34** [comment]
I will send an email.

**Comment by aamirkhan34** [comment]
@MaxHalford  I had sent an email. Were you able to check?
Thanks.

**Comment by MaxHalford** [comment]
I answered you, sorry for the delay.
