### ISSUE TITLE
Adding new classes/labels to an existing OneVsRestClassifier

### ISSUE THREAD

**Issue by aamirkhan34** [creme-ml/creme#139]
Hi team,

I am using multi-class OneVsRestClassifier for incremental learning. I am working on an Image classification problem. 
Suppose I trained a model with 5 classes, how can I add more classes to the existing model and train only on the new dataset?

**Comment by MaxHalford** [comment]
Hey, I'm not sure what you mean. The classes don't have to specified to `OneVsRestClassifier`, it just instantiates a new binary classifier when a new class is provided in the `fit_one` method.

**Comment by aamirkhan34** [comment]
When I do a prediction on a data point (let's say an image), the probability behaves like sigmoid (sum upto 1), can I change the behaviour to softmax (probability of 0-1 for all the classes/labels)?

**Comment by MaxHalford** [comment]
I'm not sure what you mean. `OneVsRestClassifier` uses the softmax function to normalize the output probabilities.

**Comment by MaxHalford** [comment]
Can I close this @aamirkhan34?

**Comment by aamirkhan34** [comment]
Sure @MaxHalford . Thanks.
