### ISSUE TITLE
Improve HalfSpaceTrees

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#140]
`HalfSpaceTrees` is now implemented in the `anomaly` module.

Here is an example using the [Shuttle dataset](http://odds.cs.stonybrook.edu/shuttle-dataset/):

```python
import scipy 
from creme import anomaly
from sklearn import metrics
from sklearn import preprocessing

shuttle = scipy.io.loadmat('shuttle.mat')

shst = anomaly.HalfSpaceTrees(n_trees=25, tree_height=15, window_size=250, scale=True, seed=42)

shuttle['X'] = preprocessing.MinMaxScaler().fit_transform(shuttle['X'])

y_true = []
y_pred = []

for x, y in zip(shuttle['X'], shuttle['y']):
    x = dict(zip(range(len(x)), x))
    y_true.append(y[0])
    y_pred.append(shst.score_one(x))
    shst.fit_one(x)
    
print(metrics.roc_auc_score(y_true, y_pred))
```

This outputs a ROC AUC score of `0.979`, which is somewhat okay, but it takes just under 3 minutes, whereas the dataset only contains 49,097 rows. However, the algorithm is very simple and is a good candidate for being written in Cython. I'm sure a huge speedup is possible. Also, the authors of the reference [paper](https://www.ijcai.org/Proceedings/11/Papers/254.pdf) say they managed to get a `0.999` ROC AUC score, which I haven't been able to reproduce.

**Comment by nicholasjin** [comment]
On my machine, running the code above produced a

`RuntimeWarning: invalid value encountered in double_scalars
  return a / b`

On my machine, I fixed it by setting `scale=False` within the HST. I can't for the life of me fathom why this should matter; minmax rescaling an already-rescaled dataset shouldn't do anything?

**Comment by MaxHalford** [comment]
Hey there. If I had to take a guess, I would that it's because one of your variables always has the same value, which leads to `max(x) - min(x) = 0` and causes a division by 0. I believe we fixed this since version `0.4.4`!

**Comment by nicholasjin** [comment]
I just checked, and I am on indeed on creme 0.4.4.

I am not sure if this is the right place to ask this, but does HST support OneHotEncoded categorical variables?

**Comment by MaxHalford** [comment]
We just have to sort a documentation issue before we release version `0.5.0`. It's fine, ask away! Yeah sure you can use one-hot encoded values. Although the performance of HST won't be very good if you have too many categories (that's a general problem with trees, they don't work in high dimensions).
