### ISSUE TITLE
Online IQR

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#143]
It would be nice to have a convenience class in the `stats` module to compute the interquartile range. This simply requires using two `Quantile` classes and returning their differences. This would be useful for using in combination with `feature_extraction.Agg`. There could be two parameters `a` and `b` to determine which quantiles to use; the default would be `a=.25` and `a=.75`.

**Comment by AdilZouitine** [comment]
I implemented it  in #144

**Comment by MaxHalford** [comment]
Good job!
