### ISSUE TITLE
Word embeddings

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#148]
It seems that there are some approaches for building word embedding online:

- [Online Learning of Word Embeddings (Medium article)](https://medium.com/explorations-in-language-and-learning/online-learning-of-word-embeddings-7c2889c99704)
- [Incremental Skip-gram Model with Negative Sampling (2017](https://www.aclweb.org/anthology/D17-1037/) with a [C++ implementation](https://github.com/yahoojapan/yskip)
- [Streaming Word Embeddings with the Space-Saving Algorithm (2017)](https://arxiv.org/pdf/1704.07463.pdf)
- [Online Learning of Interpretable Word Embeddings (2015)](https://www.aclweb.org/anthology/D15-1196)

It would nice to do a baseline implementation of one of these approaches.

**Comment by MaxHalford** [comment]
It also seems that [GloVe](https://nlp.stanford.edu/projects/glove/) is an online algorithm. [Here](http://www.foldl.me/2014/glove-python/) is a blogpost with a Python implementation.

**Comment by prise6** [comment]
This feature is no longer wanted ? 
Is there a way to see Glove Model implementation ?

**Comment by MaxHalford** [comment]
Actually it is! It's just that we moved new features to a dedicated GitHub board instead of putting them in issues.

**Comment by prise6** [comment]
Oh, Ok ! You're talking about Icebox board i assume. If we want to discuss about it, new discussion needs to be created, correct ?

**Comment by MaxHalford** [comment]
Yes I recommend that you open a thread in the discussions tab.
