### ISSUE TITLE
No wheel for 0.3.0 release

### ISSUE THREAD

**Issue by jklaise** [creme-ml/creme#149]
Just noticed that 0.3.0 is built from source, PyPI doesn't have the associated wheel present whilst 0.2.0 does, any reason for this? Thanks!

**Comment by MaxHalford** [comment]
Nice catch! I'm not sure why that happened. Version 0.4.0 should be coming in the couple of weeks.

**Comment by MaxHalford** [comment]
With version `0.4.2` being released, manylinux are now being built for Python 3.6 and Python 3.7 :)
