### ISSUE TITLE
RegressorChain similar to sklearn's MultiTaskLasso/MultiTaskElasticNet?

### ISSUE THREAD

**Issue by ronnyli** [creme-ml/creme#152]
Hi I just noticed `RegressorChain` in the documentation and I was wondering if it simply trains several independent models on the same input features or if the models share information amongst each other like they would in sklearn's [MultiTaskLasso](https://scikit-learn.org/stable/auto_examples/linear_model/plot_multi_task_lasso_support.html) and [MultiTaskElasticNet](https://scikit-learn.org/dev/modules/linear_model.html#multi-task-elastic-net).

Thanks!

**Comment by MaxHalford** [comment]
Hello. `RegressorChain` predicts the output of the first output, and then includes that prediction as a feature for predicting the second output etc. etc. I'm not an expert on both methods you mentioned, but I believe they refer to a different approach.

**Comment by ronnyli** [comment]
Ah gotcha, thanks for the clarification!
