### ISSUE TITLE
Online ARIMA

### ISSUE THREAD

**Issue by AdilZouitine** [creme-ml/creme#153]
I think it's an important thing to add creme, but it seems a little complicated to do.

- [Online ARIMA Algorithms for Time Series Prediction](https://www.aaai.org/ocs/index.php/AAAI/AAAI16/paper/download/12135/11816)
- [Online Learning for Time Series Prediction](https://arxiv.org/pdf/1302.6927.pdf)

**Comment by AdilZouitine** [comment]
A matlab implementation [here](https://github.com/nguyenduchien1994/Online_ARIMA).

**Comment by MaxHalford** [comment]
Yep, ARIMA is not an easy algorithm to implement. I'm aware of those papers, but I'm not sure of how much they are relevant. By default ARIMA is already an online algorithm because it is trained with a Kalman filter, which is by nature online.

**Comment by MaxHalford** [comment]
This is now merged into master! I pushed the envelope and added a few bells and whistles, such as exogenous variables, non-linearity, and seasonality handling. It works really well! There are some tests but a few more wouldn't hurt. I'm closing this as most of the work has been done.
