### ISSUE TITLE
Feature imputation

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#16]
It would be nice to be able to do online feature imputation. We can easily compute rolling statistics so this doesn't seem reasonable. Actually we could even do condition the feature imputation on another variable. That is, instead of simply replacing a missing value by the mean value we could actually compute a mean per value of another feature.

The trick is that missing features are usually dropped from the input features because we're using `dict`s. Either we impute all the features that have been seen but are not in the current `x`. Or else we can impute the values for which a `None` value is provided.

Feel free to propose a new implementation! I think this should be part of a new module called `impute` because this is [what scikit-learn does](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.impute).

**Comment by raphaelsty** [comment]
I'd like to try to do this new feature.
