### ISSUE TITLE
RandomForestClassifier

### ISSUE THREAD

**Issue by rmahesh123** [creme-ml/creme#160]
I am trying to utilize the RandomForestClassifier from the tree import. Here is my code:

`from creme import tree`

`model = tree.RandomForestClassifier()`

`metrics = metrics.Precision()`

`Model_selection.online_score(zip(X,y), model, metrics.Precision(), print_every=50)`

The error message that I am getting is:

`AttributeError: module ‘creme.tree’ has no attribute ‘RandomForestClassifier’`.

I am going through the example in the documentation and I do not seem to be missing any imports.

**Comment by MaxHalford** [comment]
Hey, that's probably because you're using using version `0.3.0` of `creme`, and not the latest one which is `0.4.0`. The issue is that we haven't released version `0.4.0` yet because we're having issue building manylinux wheels... You can install the latest version, which works, by running `pip install git+https://github.com/creme-ml/creme`.

**Comment by MaxHalford** [comment]
This should be fine now! Run `pip install creme --upgrade` and try again :)

**Comment by rmahesh123** [comment]
Hello Max,

Thanks for getting back to me so quickly, I will try that update. Is the new version a stable version?

Also, I am unable to use classifiers using your sklearn wrapper function. Error I am getting is there is no partial fit with that classifier.

**Comment by MaxHalford** [comment]
Yes the new version, `0.4.2`, is stable.

The error you're getting is normal: we can only wrap scikit-learn classifiers that have a `partial_fit` method.

**Comment by rmahesh123** [comment]
Hello,

Thank you for getting back. I will go ahead and pip install that.

Sincerely,



Rohin Mahesh
