### ISSUE TITLE
Inclusion of a scikit-learn wrapper like API for Keras models

### ISSUE THREAD

**Issue by sayakpaul** [creme-ml/creme#163]
Hi. 

First thanks for such a great library. I think this can be a useful feature to have. Just to give you more context, Keras allows us to wrap the models using a flexible API: https://www.tensorflow.org/api_docs/python/tf/keras/wrappers/scikit_learn. If this could be integrated into creme, I think that would be an amazing feature to have.

**Comment by MaxHalford** [comment]
If you look at the [`wrappers.py` file in the benchmarks](https://github.com/creme-ml/creme/blob/master/benchmarks/wrappers.py) then you'll see a quick and dirty implementation.

**Comment by sayakpaul** [comment]
Thanks. Mind passing on some boilerplate code so that I can quickly test it out?

**Comment by MaxHalford** [comment]
This should get you started:

```python
from creme import base
from creme import metrics
from creme import preprocessing
from creme import stream
from keras import layers
from keras import models
from keras import optimizers
from sklearn import datasets


class KerasModel:

    def __init__(self, model):
        self.model = model

    def fit_one(self, x, y):
        x = [[list(x.values())]]
        y = [[y]]
        self.model.train_on_batch(x, y)
        return self


class KerasRegressor(KerasModel, base.Regressor):

    def predict_one(self, x):
        x = [[list(x.values())]]
        return self.model.predict_on_batch(x)[0][0]


n_features = 13
inputs = layers.Input(shape=(n_features,))
predictions = layers.Dense(1, kernel_initializer='zeros', bias_initializer='zeros')(inputs)
keras_model = models.Model(inputs=inputs, outputs=predictions)
keras_model.compile(optimizer=optimizers.SGD(lr=0.005), loss='mean_squared_error')

model = preprocessing.StandardScaler() | KerasRegressor(keras_model)

X_y = stream.iter_sklearn_dataset(datasets.load_boston())

metric = metrics.MSE()

for x, y in X_y:
    y_pred = model.predict_one(x)
    print(y_pred)
    metric.update(y, y_pred)
    model.fit_one(x, y)

print(metric)
```

I can't do much more for now, I'm supposed to be on vacation!

**Comment by sayakpaul** [comment]
Thank you so much @MaxHalford. I will definitely give this a try and let you know my findings.

**Comment by MaxHalford** [comment]
@sayakpaul we've added a utility to work with PyTorch models in the `compat` module.
