### ISSUE TITLE
Running quantiles

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#17]
I've looked into computing running quantiles and it is not trivial.

References:

- [Space-Efficient Online Computation of Quantile Summaries](http://infolab.stanford.edu/~datar/courses/cs361a/papers/quantiles.pdf)
- [Online estimation of quartiles without storing observations](https://stats.stackexchange.com/questions/103258/online-estimation-of-quartiles-without-storing-observations)
- [Algorithm to dynamically monitor quantiles](https://stats.stackexchange.com/questions/7959/algorithm-to-dynamically-monitor-quantiles)

**Comment by AdilZouitine** [comment]
[Effective Computation of Biased Quantiles over Data Streams](https://www.cs.rutgers.edu/~muthu/bquant.pdf)
