### ISSUE TITLE
Dynamic features

### ISSUE THREAD

**Issue by fcpenha** [creme-ml/creme#176]
@MaxHalford Is there any way to deal with ever-changing features in the models as time evolves?

Example of use case in NLP: one selects the top N words with TF-IDF to use as features in a classification model, but the top N words change from iteration j to j+1.

Or any other case, where one needs to stop the model to redo feature selection. Would that mean the person needs to re-start the model from scratch?

**Comment by MaxHalford** [comment]
As always, it depends.

In the TF-IDF case, when you call `fit_one`, the term and document counter are incremented, and so you always up to date with the latest data. However, we haven't yet added the functionality to only consider a window of recent observations. For instance we might want to "forget" old documents. However this is really not difficult to implement. But in general `creme` supports ever-changing features, we make no assumptions about the size of corpus or anything of that sort.

Feature selection isn't something I've explored a lot in the online setting, but there are some nice and simple methods to get started. If you look at `feature_selection.SelectKBest`, it maintains a leaderboard of the current "best" features and only uses those for training. The leaderboard is updated at every iteration.

I hope I answered your questions! Please tell me if not.

**Comment by fcpenha** [comment]
Thank you @MaxHalford ! I was missing the part where *it maintains a leaderboard of the current "best" features and only uses those for training*.

**Comment by MaxHalford** [comment]
Cheers! Please do not hesitate if you have any other questions.
