### ISSUE TITLE
Issue with `progressive_val_score` 

### ISSUE THREAD

**Issue by JovanVeljanoski** [creme-ml/creme#188]
Hi, 

I am trying to use this library for some experiments I have with big-ish data. I am running into issues when using the latest master branch. The issue is reproducible with the Toulouse Bikes example (small modifications to account for recent re-structuring on creme-ml).

```
from creme import compose
from creme import linear_model
from creme import metrics
from creme import model_selection
from creme import preprocessing
from creme import datasets

X_y = datasets.toulouse_bikes.ToulouseBikes()

model = compose.Whitelister('clouds', 'humidity', 'pressure', 'temperature', 'wind')
model |= preprocessing.StandardScaler()
model |= linear_model.LinearRegression()

metric = metrics.MAE()

model_selection.progressive_val_score(X_y, model, metric, print_every=20_000)
```

Running this give me this error message:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-0dae00385f94> in <module>
     14 metric = metrics.MAE()
     15 
---> 16 model_selection.progressive_val_score(X_y, model, metric, print_every=20_000)

~/PyLibrary/creme/creme/model_selection/score.py in progressive_val_score(X_y, model, metric, on, delay, print_every)
     68             # Else update the metric and the model and remove the oldest answer
     69             if y_pred_old != {} and y_pred_old is not None:
---> 70                 metric.update(y_true=y_old, y_pred=y_pred_old)
     71             model.fit_one(x=x_old, y=y_old)
     72             del answers[0]

~/PyLibrary/creme/creme/metrics/mae.py in update(self, y_true, y_pred, sample_weight)
     34 
     35     def update(self, y_true, y_pred, sample_weight=1.):
---> 36         return super().update(x=abs(y_true - y_pred), w=sample_weight)
     37 
     38     def revert(self, y_true, y_pred, sample_weight=1.):

TypeError: update() takes no keyword arguments
```

I hope this helps,
J.

**Comment by MaxHalford** [comment]
Mmm I'm not able to reproduce this, even when running `python setup.py build_ext --inplace --force` to recompile the Cython code (`Mean` is implemented in Cython). I'm using Python 3.7.4, how about you?

By the way how is `creme` working out for you? I'm thinking that it's probably a bit slow for your needs.

**Comment by JovanVeljanoski** [comment]
Hi!

Yeah, even though I was fully up-to-date with the source from master, re-installing it seems to alleviate the issue (so do need to label this as a bug, I will close it).

As for speed/performance, I hope to try it out over the next few days on a couple of big-ish datasets (30-100GB / several hundred million to few billion samples). While speed is welcome, I put more importance (at least right now) on the "out-of-coreness", so as long as the algorithms are stable seeing so much data I am happy :).

I saw that you have a AdaBoost classifier, which is quite interesting! I hope to test it out soon:). Any other tree-based models would be very welcome, since they seem to be very popular!

Keep up the good work!:)

**Comment by MaxHalford** [comment]
Cool!

The `AdaBoostClassifier` is generic and so you can pass any classifier to it. It works pretty well in practice.

Regarding speed the big next step is to be able to cythonize `dict` operations. For instance we would like to cythonize a dot product between two vectors represented as `dict`s. I've been learning and I even bought an O'Reilly book but I'm having no luck with `dict`s. Maybe you people at @vaexio could point us in the right direction!
