### ISSUE TITLE
Prediction issue of loaded knn model by joblib

### ISSUE THREAD

**Issue by yesyigitcan** [creme-ml/creme#194]
I am trying to make a numerical prediction by using KNeighborsRegressor module of creme. In the script that I create model, I fit one row in a dataset loop and print the mean squared error results for the model. When I run the script everything looks fine and model predicts really close value. But whenever I save model by using joblib or pickle and try to use loaded model in another script. It predicts almost the same value while label value changes rapidly.

When I predict in the same script that I create the model. Results like
```
KNN Predict:  -1.5355755315278052  Real:  -1.5331041   MSE: 0.000384
KNN Predict:  -1.1927613409746234  Real:  -1.1812401   MSE: 0.000354
KNN Predict:  -1.1848814440056463  Real:  -1.1831766   MSE: 0.000354
```

When I load the model in different script, results are like
```
Predict:  -2.025035663219349  Real:  0.52935284 MSE: 2.543261
Predict:  -2.0250357400644123  Real:  -1.5166419 MSE: 3.379069
Predict:  -2.0250357388949616  Real:  -1.4899201 MSE: 3.365067
Predict:  -2.0250357341052347  Real:  -1.4390701 MSE: 3.339182
```

I have searched for the issue and found that using convert_creme_to_sklearn feature of the module 'compat' is a solution for it. I have started to use this function in my scripts to save model and feature convert_sklearn_to_creme function to load the model. But this time model started to predict 0 for each row of the same dataset.

It is like
```
Predict:  0  Real:  -1.6145542 MSE: 1.392475
Predict:  0  Real:  -1.936667 MSE: 1.630176
Predict:  0  Real:  -2.027085 MSE: 1.705379
Predict:  0  Real:  -2.0280786 MSE: 1.706027
```

I am really confused about correct use of wrapper objects and how to save and load models are created by creme.

Script where I create model
```
with open('..\\dataset.csv') as csv_file:
    knn = KNeighborsRegressor()
    knn_scorer = MSE()
    reader = csv.reader(csv_file)
    next(csv_file)
    for row in reader:
        if int(row[-1]) > 5:
            break
        x = {
            "f1" : float(row[4]),
            "f2" : float(row[9]),
            "f3" : float(row[10]),
            "f4" : float(row[11])
        }
        y = float(row[8])
        knn_scorer.update(y, knn.predict_one(x))
        print(row[-1], " KNN Predict: ", knn.predict_one(x), " Real: ", y, " ", knn_scorer)
        knn.fit_one(x, y)
filename = 'knn_model.pkl'
sk_model = convert_creme_to_sklearn(knn)
joblib.dump(sk_model, filename)
```
########################################
Script where I load model and predict

```
filename = 'knn_model.pkl'
sk_model = joblib.load(filename)
model = convert_sklearn_to_creme(sk_model)
print(type(sk_model))
print(type(model))

with open('..\\dataset.csv') as csv_file:
    scorer = MSE()
    reader = csv.reader(csv_file)
    next(csv_file)
    for row in reader:
        if int(row[-1]) > 5:
            break
        x = {
            "f1": float(row[4]),
            "f2": float(row[9]),
            "f3": float(row[10]),
            "f4": float(row[11])
        }
        y = float(row[8])


        scorer.update(y, model.predict_one(x))
        print(row[-1], " Predict: ", model.predict_one(x), " Real: " , y, scorer)
```

**Comment by MaxHalford** [comment]
Thanks for opening the issue! I think I know where this is coming from. It's late where I am but I'll look at this first thing in the morning.

**Comment by MaxHalford** [comment]
I took a look at it. I don't have your `dataset.csv` so I tested it with dummy data. On the master branch I don't seem to have any problems.

Can you install the latest version with `pip install git+https://github.com/creme-ml/creme` and tell me if the problem persists?

Normally you don't to convert to a sklearn model to be able to pickle correctly. You can pickle as so:

```python
import pickle

with open('tmp.pkl', 'wb') as f:
    pickle.dump(model, f)
    
with open('tmp.pkl', 'rb') as f:
    model = pickle.load(f)
```

**Comment by yesyigitcan** [comment]
I am already using the lastest version of creme. Using pickle as you declared has not affected the results.

`pip show creme`
```
Name: creme
Version: 0.4.4
Summary: Incremental machine learning in Python
Home-page: https://github.com/creme-ml/creme
Author: Max Halford
Author-email: maxhalford25@gmail.com
License: BSD-3
Location: c:\users\**\appdata\local\programs\python\python37\lib\site-packages
Requires: scikit-learn, scipy, numpy
Required-by:
```
Here is the link of the dataset that I use for the model.
https://www.kaggle.com/wkirgsn/electric-motor-temperature

You can find my scripts in the links below

Model creation
https://github.com/yesyigitcan/online-learning-electric-motor-dataset-with-creme/blob/master/knn_model.py

Loading model created
https://github.com/yesyigitcan/online-learning-electric-motor-dataset-with-creme/blob/master/load_knn_model.py

I want to see consistent prediction change while real value is changing. But it predicts around -2.0250357389. It doesn't matter if real value is -1.4900979 or 2.1835442

**Comment by MaxHalford** [comment]
Version `0.4.4` is the latest release but it isn't the bleeding development version. You can install the latest version with `pip install git+https://github.com/creme-ml/creme --upgrade`.

In the meantime I'll try out your code :)

**Comment by MaxHalford** [comment]
@yesyigitcan I ran your scripts and now I understand where your incomprehension is coming from! The trick is that `KNeighborsRegressor` stores and uses the latest `n` observations to make predictions. If you don't call `fit_one` then these observations won't be updated, which is why your predictions are worse when you load the model and predict over the whole file. Usually in an online setting the training and prediction phases are interleaved so this issue doesn't happen.

Hopefully I'm clear, but please insist if I wasn't!

**Comment by yesyigitcan** [comment]
@MaxHalford thank you for your support to my problem. Now I understand what you point. I am totally satisfied about your explanation. May I ask you another question? If I get the target value in a long time and have to predict new records that are not close numerically, I mean if I want to keep my model successful as long as it can be even it cannot get the right value (target), what would be the best approach or algorithm to update my model on numerical data? Assume that data doesn't spread on a linear line and it is so costly to train whole data at once in periods.

My question may sound complicating. Please ask me the points that you are not clear with.
I am working for our academic thesis on online learning with my two friends. Your answers are so valuable for our academic research.

**Comment by MaxHalford** [comment]
I'm not too sure what you mean. Usually you just make predictions and learn as soon as the truth is made available. Instead of having a separate script for training and testing both are inter-leaved.

I would appreciate a more detailed explanation/example :)

**Comment by MaxHalford** [comment]
@yesyigitcan how's it going?

**Comment by yesyigitcan** [comment]
@MaxHalford  we gave a break for project. But we're going to continue in second term of the university (next month). We will compare incremental learning and classical  (train at once) approach for a long time period and prepare a report for it. We have not made definite plan of the implementation yet. But we have some ideas for possible implementations. We aim to show benefits and losses of incremental learning. I can inform you about the process and any confusing points during the study, if you want. Thanks for asking. Have a good day!

**Comment by MaxHalford** [comment]
Sounds good!

**Comment by MaxHalford** [comment]
How's it going @yesyigitcan? :)

**Comment by yesyigitcan** [comment]
Hi @MaxHalford . Thanks for your interest to the project :D
We have written some scripts to imitate the process of handling with the instant data. We have a data set about the test results of a car electric motor. A script reads data from this data set and transfer a data row to specified directory at uncertain intervals (random seconds or minutes between a range limit). So we believe that we can imitate the process of new data that is received from a source (mobile application, website, new test entry for a car etc.) instantly.
We are going to train a model incrementally by using this new data and also store it into a database to train another model by using some other libraries that perform fully training except creme. After monitoring this process for a time, we analyze the performance results, accuracy results etc. to document the comparison of these two approaches (incremental learning and classical train at once approach). 
You can reach the code by using following link
https://github.com/yesyigitcan/Real-Time-Big-Data-Analytics
The scripts have been written to make a start and will be updated during the project duration.

If you have any idea, suggestion or feedback for the project, I really would like to hear.
I will be informing you about the project whenever you want to hear about it.

I wish you good and healthy days :)

**Comment by MaxHalford** [comment]
That sounds really cool, especially for a university project! On my side I've written a script to simulate a script to simulative taxi traffic in New-York city, you can see it [here](https://github.com/creme-ml/chantilly/tree/master/examples/taxis). The goal is to showcase `chantilly`, which is going to be the de facto tool to send a `creme` model into production. For the moment it only provides an API, but soonish it will also display an interface to monitor the model in real-time. 

I'll take a look at your code :). Healthy and joyful days to you too.

**Comment by yesyigitcan** [comment]
Hi @MaxHalford . Our thesis project is finally done and we made a presentation in the university. Thank you for this useful tool. It was really easy to use and it really helped us for the project. You are really good at this field as far as I see in different platforms. I hope I can be good at this field just like you. Keep up the good work!
If you are still interested, you can use the link below to go to our presentation slide
https://docs.google.com/presentation/d/1CVTvuwjEMOVgcpK8vCRbh5Bk-J7Kf7H2k7lOTtAhuJ4/edit?usp=sharing

Have a good day :)

**Comment by MaxHalford** [comment]
Thank you for the kind words @yesyigitcan! I'm so happy that our work was useful to you. Keep up the good work too, you're doing well. Hopefully we'll meet again in other circumstances :)
