### ISSUE TITLE
Mirror descent

### ISSUE THREAD

**Issue by choltz95** [creme-ml/creme#206]
Important algorithm: [reference](https://blogs.princeton.edu/imabandit/2013/04/16/orf523-mirror-descent-part-iii/)

**Comment by MaxHalford** [comment]
Yeah mirror descent seems interesting, there's a good detailed explanation [here](https://parameterfree.com/2019/09/26/online-mirror-descent-i-bregman-version/) and [here](https://fredzhang.me/pdf/note/mirror-descent.pdf), and some intuition [here](https://www.quora.com/What-is-mirror-descent-and-how-is-it-different-from-gradient-descent). However I haven't managed to find a nice implementation. [Here](https://people.cs.umass.edu/~akshay/courses/cs690m/files/lec16.pdf) it states that online mirror descent is simply FTRL.

**Comment by MaxHalford** [comment]
Added this to the [icebox](https://github.com/creme-ml/creme/projects/2).
