### ISSUE TITLE
Drift detection

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#209]
I think it would be good to have a discussion about how we want to handle drift detection. There are different kinds of drift (performance of a model, feature distribution...). [Here](https://www.win.tue.nl/~mpechen/publications/pubs/Gama_ACMCS_AdaptationCD_accepted.pdf) is an academic survey. We should probably start to define what cases we want to handle, and then define an API. From what I have gleaned practitioners would first and foremost be interested by a simple way to monitor the performance of a model and receive alerts whenever the performance drops "significantly".

This is going to require a bit of research and foresight before actually implementing something concrete.

**Comment by kivo360** [comment]
What's the status on this?

**Comment by MaxHalford** [comment]
Well I know what to do, but we're actually looking at merging with another online machine learning library that already does this. Things should be moving in the upcoming summer.

**Comment by MaxHalford** [comment]
Added this to the [icebox](https://github.com/creme-ml/creme/projects/2).
