### ISSUE TITLE
Add multiple metrics support in progressive_val_score

### ISSUE THREAD

**Issue by gbolmier** [creme-ml/creme#211]
It would be nice if `model_selection.progressive_val_score` could support a list of metric to print instead of just one

**Comment by MaxHalford** [comment]
With the development version you should be able to do:

```
from creme import metrics

m = metrics.MAE() + metrics.MSE()
```

You can then pass `m` to `progressive_val_score`.

I haven't tested this much so please tell me if something goes wrong!

**Comment by gbolmier** [comment]
Just tried and works perfectly, thx :+1:

**Comment by shaksham95** [comment]
Hey @MaxHalford ,

I am trying to add multiple metrics using the above solution but I am getting the following error:

![image](https://user-images.githubusercontent.com/7498849/75744771-53497c80-5d3b-11ea-90df-32e209b1e22e.png)

Is there a way by which I can use these two metrics together?

**Comment by MaxHalford** [comment]
Hey @shaksham95! You're not doing anything wrong, it's just that `ConfusionMatrix` isn't a metric per say and therefore it can't be mixed with other metrics. I'll fix that for the next release! Thanks a lot.
