### ISSUE TITLE
reco module models support

### ISSUE THREAD

**Issue by gbolmier** [creme-ml/creme#212]
Currently `reco` module models have a different API compared to other models in `creme`:
- they don't inherit from `creme.base.Estimator` that handles `Pipeline` and `TransformerUnion` compatibility. This first point could be easily solved by making `reco.base.Recommender` inherits from `creme.base.Estimator`
- they expect a two variable input (`r_id` and `c_id`) instead of a dictionnary which make them incompatible with `progressive_val_score` and `successive_halving` (hope I don't forget other utilities). As discussed with @MaxHalford, it should be possible to make those methods work with this different type of model input

**Comment by MaxHalford** [comment]
I totally forgot about this, sorry!

- Yeah I suppose everything should work fine if `Recommender` inherits from `Estimator`. There might be some edge-cases but I'm sure they'll be easy to handle.
- This takes a bit more thinking, but it's manageable. I'll get something done in the afternoon and tell you when :)

**Comment by MaxHalford** [comment]
Actually I just took a look and it's a bit difficult to adapt `progressive_val_score` without breaking the API, which isn't something I want to do. It seems that the "easiest" solution is to pass dicts to the update method of each recommender. The dicts will need to contain the `user` and `item` keys. It's a bit ugly because the keys are imposed, but it's not that bad. The advantage is that we can add other keys if required. For example we can add a `timestamp` key to use with the `on` parameter of `progressive_val_score`.

Thoughts @gbolmier? Sorry I should have looked at this much earlier.

**Comment by gbolmier** [comment]
No worries Max! Thx for the prompt reply :)

I agree with your first solution, using dicts as inputs seems better as it avoid a lot of compatibility issues (e.g. datasets generating dicts). I also like your 2nd solution but the inherited `fit_one` must therefore know which keys to unpack right?

Imposed keys being the only drawback to the 1st solution. If I'm not wrong, as we handle item recommendation case and not social recommendation from graphs, using `user` and `item` keys makes sense for all the case we cover right now.

Any opinion @VaysseRobin?

**Comment by MaxHalford** [comment]
Indeed @gbolmier `fit_one` must know which keys to unpack, but at least that logic is only in one place. Yeah for the moment `user` and `item` LGTM.

**Comment by gbolmier** [comment]
Sounds good to me! I was wondering if we should allow the users to pass optional arguments to the inherited  `fit_one(self, x, y, row_key='user', col_key='item')` or force them to stick with `user` and `item` keys?

You can assign me this task and I will merge the changes within the FM pull request #187

**Comment by MaxHalford** [comment]
> Sounds good to me! I was wondering if we should allow the users to pass optional arguments to the inherited `fit_one(self, x, y, row_key='user', col_key='item')` or force them to stick with `user` and `item` keys?

For the moment let's stick with `user` and `item`.

> You can assign me this task and I will merge the changes within the FM pull request #187

Will do!
