### ISSUE TITLE
Random trees embedding

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#213]
See [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomTreesEmbedding.html#sklearn.ensemble.RandomTreesEmbedding). This uses random trees, which is identical to `HalfSpaceTrees` in the `anomaly` module. It would be nice to reuse that code instead of duplicating the logic.

**Comment by choltz95** [comment]
What do you think about benchmarking [RP-Tree](http://cseweb.ucsd.edu/~dasgupta/papers/rptree-stoc.pdf ) & [RP-Embedding](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.random_projection)

**Comment by MaxHalford** [comment]
I didn't know about random projections! Yeah that would be a good idea; it would be even better if they can be implemented online.

**Comment by choltz95** [comment]
I think online rp-embedding is amenable to approximate matrix multiplication algorithms. A streaming algorithm for RP-Trees is given in [appendix 1.](http://cseweb.ucsd.edu/~dasgupta/papers/rptree-tr.pdf)

**Comment by MaxHalford** [comment]
Nice, I didn't see that. I opened a specific issue, see #215. I haven't taken the time to look at both techniques in detail but they seem very similar.

**Comment by MaxHalford** [comment]
[The Mondrian Kernel](https://arxiv.org/pdf/1606.05241.pdf) is also worth taking into account.

**Comment by MaxHalford** [comment]
Added this to the [icebox](https://github.com/creme-ml/creme/projects/2).
