### ISSUE TITLE
Prediction clipping

### ISSUE THREAD

**Issue by gbolmier** [creme-ml/creme#216]
Hey guys! It would be nice to add a generic way to clip predictions. I was thinking of a `creme.postprocessing` module (for prediction postprocessing) where we could do that kind of stuff

**Comment by MaxHalford** [comment]
That's a good idea! However API-wise I think this should go in the `meta` module, at least for the moment.

**Comment by gbolmier** [comment]
Just took a closer look and seems like we have to make some changes in the `Pipeline` class. 

Currently, the pipeline mechanism assume a `final_estimator` as last step which can't hold with another transformer after the prediction.

For the moment I'm not enough familiar with the code to suggest a solution (may not be that easy btw). Don't have the time to go deeper tonight, keep you posted :kissing_closed_eyes:

**Comment by MaxHalford** [comment]
I think you can make it so that the prediction clipper inherits from `base.Classifier`, no? `meta.TransformedTargetRegressor` inherits from `base.Regressor` and works fine :)

**Comment by gbolmier** [comment]
My bad @MaxHalford! I should had looked closer to what's already in the `meta` module, thanks for the clue.

I implemented a `PredClipper` inheriting from `base.Regressor` and `base.Wrapper`, everything works well! Just had to add a `labelloc` property to `base.Wrapper` for model drawing (indicates the relative location of the subroutine label to the wrapped model):

![Screenshot from 2020-01-11 21-02-41](https://user-images.githubusercontent.com/25319692/72210032-c231f400-34b5-11ea-9fa1-8249a48b6a53.png)

Will merge the changes within the FM pull request #187 if it's good for ya

**Comment by gbolmier** [comment]
One more thing, models can't be drawn if not chained with other steps as a pipeline, we need to do:

```python
from creme import compose
from creme import linear_model

model = compose.Pipeline(
    [
        meta.PredClipper(
            regressor=linear_model.LinearRegression(),
            y_min=0,
            y_max=10
        )
    ]
)

model.draw()
```

What do you think of making `base.Estimator` inherits from `Pipeline`?

**Comment by MaxHalford** [comment]
No worries, it's hard to remember everything in the API, `creme` is getting big ;). Mmm I'm not sure if that makes sense, but why not! You could also add a `draw` method to `BaseEstimator` and wrap the estimator inside a `Pipeline` as you just did in the example. That's probably a nicer solution. The thing I don't like about inheriting from `Pipeline` is that it's going to add many methods and attributes to each class and will bloat the documentation.

**Comment by gbolmier** [comment]
Yeah that's really exciting, a lot of good things to come :heart_eyes:

Agree with you, inheriting from `Pipeline` would be too heavy unfortunately... let's stick with the pipeline wrapping solution, at the end it's not something that is going to be used every day
