### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch>=1.3.1

### ISSUE THREAD

**Issue by greatsharma** [creme-ml/creme#218]
on running `pip install -e ".[dev]"` it gives this error

`ERROR: Could not find a version that satisfies the requirement torch>=1.3.1 (from creme==0.4.4) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)`
`ERROR: No matching distribution found for torch>=1.3.1 (from creme==0.4.4)`

**Comment by MaxHalford** [comment]
Hey there! I can't look into this right but I will by next week.

**Comment by greatsharma** [comment]
@MaxHalford  whenever you got time do look at once. 

In the first attempt I got the above mentioned error. But in the second attempt it worked. But then on running `conda install -c anaconda gcc` it throwed error but I think it might be probably because my system already has gcc( `gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) ` ) And then finally it worked.

But on running `pytest` it gives error `Command 'pytest' not found` but I think it should be installed in `[dev]` mode . Then I `pip install pytest` but it's not clear how to run tests. In any case it gives the following error - 
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --doctest-cython --cov-config=.coveragerc
  inifile: /home/winter_soilder/Study/Repos/creme/pytest.ini
  rootdir: /home/winter_soilder/Study/Repos/creme
```

In any case I struggled a bit, it may be the case that these problems are entirely from my side but I insist to check them once. I think if all tests are placed in a single folder named `tests` than it would have been easier. 

Also please explain how to run test because it's not working atleast the way I use pytest.

**Comment by greatsharma** [comment]
I think this was the problem from my side only.
