### ISSUE TITLE
Reading and training concurrently

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#234]
I would like to explore the possibility of reading data in one thread and training a model in another thread. For instance we should be able to read from a CSV file in one thread and train a model in another thread at the same time. While the model is training on one mini-batch, the next mini-batch can be prepared at the same time. AFAIK this is what PyTorch's `DataLoader` is for. 

I've had a quick at it but it didn't bring any performance boost. Here is the code:

```python
import concurrent.futures
import itertools
import queue

from creme import compose
from creme import datasets
from creme import linear_model
from creme import metrics
from creme import preprocessing


def produce(q, stream):

    for batch in stream:
        q.put(batch)

    q.put(queue.Empty)


def consume(q, model, metric):

    while True:
        batch = q.get()
        if batch == queue.Empty:
            break
        for x, y in batch:
            yp = model.predict_one(x)
            metric.update(y, yp)
            model.fit_one(x, y)


metric = metrics.ROCAUC()

model = compose.Pipeline([preprocessing.StandardScaler(), linear_model.LogisticRegression()])

X_y = datasets.CreditCard().take(20000)

q = queue.Queue(maxsize=1)

def chunk_input_stream(input_stream, chunk_size):
    while True:
        chunk = list(itertools.islice(input_stream, chunk_size))
        if chunk:
            yield chunk
        else:
            return

with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
    executor.submit(produce, q, chunk_input_stream(X_y, 32))
    executor.submit(consume, q, model, metric)
```

And here is the "straightforward" version:

```python
from creme import compose
from creme import datasets
from creme import linear_model
from creme import metrics
from creme import preprocessing


metric = metrics.ROCAUC()

model = compose.Pipeline([preprocessing.StandardScaler(), linear_model.LogisticRegression()])

X_y = datasets.CreditCard().take(20000)

for x, y in X_y:
    yp = model.predict_proba_one(x)
    metric.update(y, yp)
    model.fit_one(x, y)

print(metric)
```

**Comment by gbolmier** [comment]
I'm not an expert in parallel computing, from what I know Python multithreading only executes one thread at any given time. See [here](https://stackoverflow.com/a/18114882) and [here](https://medium.com/contentsquare-engineering-blog/multithreading-vs-multiprocessing-in-python-ece023ad55a) for detailed explanations

**Comment by MaxHalford** [comment]
Yep I totally get that. But, if a job is I/O dependent (such as reading a CSV file from the disk), then concurrency [can help](https://realpython.com/python-concurrency/).

**Comment by gbolmier** [comment]
IMO the problem here is that our program isn't spending significant time waiting for something to happen to benefit from concurrency... sorry if I'm wrong, I'm not very experienced with those things

**Comment by MaxHalford** [comment]
Yeah you're probably right!

**Comment by MaxHalford** [comment]
I'm happy to close this now. Reading speed was bothering me a bit, but now that we have implemented `stream.Cache` reading is less of a bottleneck.
