### ISSUE TITLE
Problems with Imbalanced Dataset Notebook

### ISSUE THREAD

**Issue by shaksham95** [creme-ml/creme#236]
Hey Team,

I have recently started using creme to explore incremental learning as a part of one of my projects at my company. However, while I am trying to follow the steps mentioned in _**imbalanced-learning.ipynb**_, I am facing the following issues:-

- `datasets.CreditCard()` - throws **"AttributeError"**. Possible solution is to use `datasets.fetch_credit_card()`
![image](https://user-images.githubusercontent.com/7498849/74507557-c624bc00-4f22-11ea-8a63-6fe6d8cff85c.png)

- `counts = collections.Counter(y for _, y in X_y)` throws _**invalid literal for int() with base 10: '1e+05'**_ error. A possible workaround is to change line number 265 `x[i] = t(x[i])` in _**stream.py**_ to `x[i] = t(float(x[i]))`

- `model_selection.progressive_val_score(X_y, model, metric, print_every=15_000, show_time=True)` also throws "**AttributeError**"
![image](https://user-images.githubusercontent.com/7498849/74507801-78f51a00-4f23-11ea-9954-fa0e79d3f206.png)
Possible solution is to use `model_selection.online_score(X_y, model, metric, print_every=15_000)`

- while executing `model_selection.online_score(X_y, model, metric, print_every=15_000)` **"StopIteration"** pops up. I tried looking for a possible solution but I am not sure here should the changes be made in order to make it work.
![image](https://user-images.githubusercontent.com/7498849/74507952-e6a14600-4f23-11ea-997a-0cbe63ce7400.png)

Please help me out with this?
_**Creme version: 0.4.4**_

Thanks
Shaksham

**Comment by MaxHalford** [comment]
Hey there! That notebook is using code that is only available on master. To make it work you have to install the latest development version. If all goes to plan we will be releasing version 0.5 somewhere during April.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MaxHalford** [comment]
@shaksham95, version `0.5.0` is now available :)
