### ISSUE TITLE
Encountered Multiple Runtime Warnings When Training SVD Model

### ISSUE THREAD

**Issue by gokhangerdan** [creme-ml/creme#240]
Encountered multiple runtime warnings when training a SGD optimized SVD recommendation model.

Code:
```
ratings = df.to_records(index=False)

model = reco.SVD(
    row_optimizer=optim.SGD(0.005),
    col_optimizer=optim.SGD(0.005),
    random_state=42
)

for item1, item2, rating in ratings:
    _ = model.fit_one(item1, item2, rating)
```

Output:
```
/home/ggerdan/Desktop/online_learning/onlinelearningenv/bin/python /home/ggerdan/Desktop/online_learning/train.py
/home/ggerdan/Desktop/online_learning/onlinelearningenv/lib/python3.6/site-packages/creme/reco/svd.py:123: RuntimeWarning: overflow encountered in multiply
  c_grad_vec = {c_id: loss_gradient * self.row_vec[r_id] + self.l2 * self.col_vec[c_id]}
/home/ggerdan/Desktop/online_learning/onlinelearningenv/lib/python3.6/site-packages/creme/reco/svd.py:123: RuntimeWarning: invalid value encountered in multiply
  c_grad_vec = {c_id: loss_gradient * self.row_vec[r_id] + self.l2 * self.col_vec[c_id]}
/home/ggerdan/Desktop/online_learning/onlinelearningenv/lib/python3.6/site-packages/creme/reco/svd.py:115: RuntimeWarning: overflow encountered in multiply
  r_grad_vec = {r_id: loss_gradient * self.col_vec[c_id] + self.l2 * self.row_vec[r_id]}
/home/ggerdan/Desktop/online_learning/onlinelearningenv/lib/python3.6/site-packages/creme/reco/svd.py:115: RuntimeWarning: invalid value encountered in multiply
  r_grad_vec = {r_id: loss_gradient * self.col_vec[c_id] + self.l2 * self.row_vec[r_id]}
```

**Comment by MaxHalford** [comment]
@gbolmier 

@gokhangerdan is there any way you provide us the `df` variable?

Also, looking, at your code, I assume you're using `creme==0.4.4`? If so could you try installing the latest development version via `pip install git+https://github.com/creme-ml/creme --upgrade`? @gbolmier has made some substantial changes to the `reco` module that might fix your issue.

**Comment by gokhangerdan** [comment]
@MaxHalford 

download link to df ('df.csv'): https://we.tl/t-B0LmtuPdCI

```
import pandas as pd
df = pd.read_csv("df.csv")
```

**Comment by VaysseRobin** [comment]
I just figured out that there was a bug in the svd.py file at line 111: 
```
# Update row bias
r_grad_bias = {r_id: loss_gradient + self.l2 * self.col_biases[r_id]}
```
Should be:
```
# Update row 
r_grad_bias = {r_id: loss_gradient + self.l2 * self.row_biases[r_id]}
```

Maybe it could be the reason of the issue, but with the new release, it will be corrected.

**Comment by gokhangerdan** [comment]
@VaysseRobin @MaxHalford thanks for quick response :)

But how safe is it to use it as it is now?

**Comment by MaxHalford** [comment]
@gokhangerdan honestly version 0.5 will bring a lot of changes to the `reco` module. For instance the `SVD` class has been renamed and refactored. If I were you, I would either wait for the new release, or if time is pressing I would install the development version.

**Comment by gbolmier** [comment]
Hi @gokhangerdan :)

Thanks for providing the data! Turns out your target variable has a large spread of values (from 10 to 1320):

![Screenshot from 2020-02-21 10-41-03](https://user-images.githubusercontent.com/25319692/75023472-245c1c80-5498-11ea-9ebc-fbfbcb5d7670.png)

Therefore scaling will definitely help, I suggest you to try a log transform as a first step. 

Given that I bet you could also obtain better accuracy if you could increase the size of your dataset (214 samples).

As @MaxHalford said `reco` module has been significantly updated recently, that's why I also encourage you to use the current development version. Hope it helps, feel free to come back to us if you have any other issues

**Comment by VaysseRobin** [comment]
@gokhangerdan you can check out [this notebook](https://github.com/creme-ml/creme/blob/master/docs/notebooks/matrix-factorization-for-recommender-systems.ipynb) from @gbolmier to have an idea on how to use the new API.

**Comment by gokhangerdan** [comment]
@gbolmier @VaysseRobin @MaxHalford 
Thank you all. You were very helpful.
