### ISSUE TITLE
Incremental learning algorithm pre trained for regression

### ISSUE THREAD

**Issue by ninou2012** [creme-ml/creme#242]
Hi all
Phd student from Algéria
I use machine learning in my research in oil drilling in problem of regression i use Random forest
but I need to use Incremental learning algorithm pre trained for regression for generalization i try to use Adaptive random forest with MOA framework
Can you give other algorithm better than ARF in python for example
thank you
Djamil Rezki
Phd student Batna 2 University Algeria
drezki@gmail.com
tel : 213 698 36 21 15 (viber + whatsApp)

**Comment by MaxHalford** [comment]
Hey, you've opened the same issue twice, so I'll close this copy and answer you on the other one.
