### ISSUE TITLE
Stream utility for SQLAlchemy

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#249]
It should be pretty easy to iterate over a result from SQLAlchemy. It would be nice if there was an example in the user guide. We can then judge if the code is complex enough to merit a utility in the `stream` module.

**Comment by 3outeille** [comment]
Hey, I would like to give it a try. Can you assign me this task please ?

**Comment by MaxHalford** [comment]
Done! Take your time with this. Ideally it would be nice to include an example with one or two joins :).

**Comment by 3outeille** [comment]
@MaxHalford For the function, do we assume that the user already created the engine ? (I'm learning SQLAlchemy on the fly)

**Comment by MaxHalford** [comment]
Good question! I think we can use as a reference the `con` parameter of [`pandas.read_sql`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html). Pandas is flexible and seems to allow providing an engine, a connection, or a string address. I think that providing an engine and/or a connection is good enough.

To answer your question specifically: yes, we should assume that the user is capable of creating the engine.

**Comment by 3outeille** [comment]
Hi, sorry to bother you again. I feel like I'm misunderstanding something.

My initial attempt was to:

1- Load the database.
2- For each table in the database:
   - Fetch all rows of the table.
   - For each row: 
      - Yield it.

So, what I have to do now is to do the same thing but this time, over a query right?

Thus, the function should look like:

```python 
def iter_sql(query, con):
    ...
```
where I should yield one row at the time from the query ?

**Comment by MaxHalford** [comment]
> Hi, sorry to bother you again. I feel like I'm misunderstanding something.

Don't worry you're no bother.

> So, what I have to do now is to do the same thing but this time, over a query right?

Yeah the idea is to yield the results of a query.

> where I should yield one row at the time from the query ?

I'm not sure I understand your question. With SQLAlchemy it's possible to loop over the results of a query as they are processed by the database. In other words, instead of called `query_result.all()`, you simply have to loop over the result because it's a generator. There are [many examples](https://www.google.com/search?client=firefox-b-d&q=sqlalchemy+loop+over+results) of this online.

**Comment by 3outeille** [comment]
Thanks for you quick answer ! I'll take a look
