### ISSUE TITLE
Add more parameters for TfidfVectorizer

### ISSUE THREAD

**Issue by kinoute** [creme-ml/creme#253]
Hi,

Great library! I'm trying to port a nice SGDClassifier running on Sklearn to the world of online training with Creme but I'm having some problems.

Here is my pipeline:

```py
text_clf_svm = Pipeline([
                            ('vect', TfidfVectorizer(
                                preprocessor=clean_email,
                                ngram_range=(1, 2),
                                strip_accents='unicode',
                                lowercase=True,
                                sublinear_tf=False,
                            ))
                            ,
                            ('clf-svm', SGDClassifier(loss='hinge', 
                                                   penalty='l2',
                                                   alpha=1e-4,
                                                   max_iter=500,
                                                   early_stopping=True,
                                                   class_weight="balanced",
                                                   random_state=42,
                                                   n_iter_no_change=10
                                                ))])

```

As you can see, I use a custom `preprocessor` named `clean_email` and a custom `ngram_range`. Unfortunately, it doesn't seem to be possible to use these sklearn parameters on Creme, they don't seem to be available. 

Is there any chance we could have it or use a sklearn pipeline on Creme ? I tried `creme.compat.convert_sklearn_to_creme ` to convert my pipeline but it didn't work.

Regards,

Yann

**Comment by MaxHalford** [comment]
Hello there. I believe that the issue is that scikit-learn's `TfidfVectorizer` does not have a `partial_fit` method, and therefore can't be used in an online context. You could however use creme's TF-IDF implementation.

**Comment by MaxHalford** [comment]
We already have an online vectorizer, as documented [here](https://creme-ml.github.io/generated/creme.feature_extraction.TFIDFVectorizer.html#creme.feature_extraction.TFIDFVectorizer). But indeed you could use the project you linked as well.

**Comment by kinoute** [comment]
I understand that you have an online vectorizer, but what about the missing functionalities like `ngram_range` or `pre-processor`? Do I have to do it all by myself before using your online vectorizer or there is a way to integrate these features in your version of Tfidf and later in creme pipeline? Are these functions the reason why there is no `partial_fit` functionality?

Thank you!

**Comment by MaxHalford** [comment]
Ahah, now I understand your question :). `ngram_range` and `preprocessor` are simply not implemented in `creme`. There's no reason why they can't be implemented!

**Comment by kinoute** [comment]
I can try to make a PR for the n-grams first but honestly, my skills are not that great. Since there is already a function called `preprocessor` in your class, that might need some thinking.

**Comment by MaxHalford** [comment]
Don't worry about anything, I'm taking a 4 hour train ride tonight, I'll take care of it :).

**Comment by kinoute** [comment]
Awesome, can't wait to play with it! Thanks!

**Comment by MaxHalford** [comment]
@kinoute version `0.5.0` is out, you can try out the 2 new parameters in `feature_extraction.TFIDF` :)
