### ISSUE TITLE
MultiOutputClassifier example?

### ISSUE THREAD

**Issue by gonzoramos** [creme-ml/creme#259]
Hi all,

I am new to using creme and I would like to use it for some projects - I am interested in the MultiOutputClassifier, but I cannot find examples of how to use it. Unfortunately, the documentation does not include any examples.

Also, how does one save and load models?

Many thanks in advance!

**Comment by gbolmier** [comment]
Hey @gonzoramos, thanks for your interest in the library :)

We didn't write about the multioutput setting in the user guide but we do have a short example in the documentation, see [here](https://creme-ml.github.io/generated/creme.multioutput.ClassifierChain.html#creme.multioutput.ClassifierChain).

You can save and load your models by serializing them with the Python `pickle` module:
```python
import pickle

# save
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)
    
# load
with open('model.pkl', 'rb') as f:
    model = pickle.load(f)
```

Hope it helps, cheers!

**Comment by gonzoramos** [comment]
Thank you! I will give these tips a try.

**Comment by blackmask-acuity** [comment]
> Hey @gonzoramos, thanks for your interest in the library :)
> 
> We didn't write about the multioutput setting in the user guide but we do have a short example in the documentation, see [here](https://creme-ml.github.io/generated/creme.multioutput.ClassifierChain.html#creme.multioutput.ClassifierChain).
> 
> You can save and load your models by serializing them with the Python `pickle` module:
> 
> ```python
> import pickle
> 
> # save
> with open('model.pkl', 'wb') as f:
>     pickle.dump(model, f)
>     
> # load
> with open('model.pkl', 'rb') as f:
>     model = pickle.load(f)
> ```
> 
> Hope it helps, cheers!

The mentioned link seems to be death.

**Comment by gbolmier** [comment]
I updated the link @blackmask-acuity
