### ISSUE TITLE
Add partial_fit to scikit-learn wrappers

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#267]
We should add `partial_fit` methods to the `compat.Creme2SKL*` wrapper classes. At the same time it would be good to test if converting an `sklearn` model to a `creme` model, and then back again to an `sklearn` model produces a class which passes the `sklearn.estimator_checks.check_estimator` test suite.

**Comment by brcharron** [comment]
I gave this one a go, please have a look at the PR #312.

**Comment by MaxHalford** [comment]
Thanks @brcharron for taking care of this.
