### ISSUE TITLE
Drawing decision trees

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#268]
@raphaelsty is on it @rmahesh123 :)

**Comment by raphaelsty** [comment]
Here are the useful resources:

 https://scikit-learn.org/stable/modules/generated/sklearn.tree.plot_tree.html#sklearn.tree.plot_tree

https://www.graphviz.org

 https://github.com/parrt/dtreeviz (overkill?)

**Comment by rmahesh123** [comment]
@MaxHalford @raphaelsty Thanks for the heads up and resources! I tried sklearn plot_tree but it was not working on my end. I will try and use dtreeviz to see if that works.

**Comment by raphaelsty** [comment]
Hi @rmahesh123, in cooperation with Max we have made good progress and the PR seems ready to be merged. You will be able to use this new feature by installing the development branch once the pull request has been validated and marged by @MaxHalford . 

```python
from creme import datasets
from creme import tree


model = tree.DecisionTreeClassifier(
    patience=10,
    confidence=0.8,
    criterion='gini',
    max_depth = 10,
    tie_threshold = 0.05,
    min_child_samples = 0,
)

for x, y in datasets.Phishing():
    
    model.fit_one(x, y)

model.draw(max_depth=3)
```

<img width="884" alt="image" src="https://user-images.githubusercontent.com/24591024/77231092-f5b98a80-6b98-11ea-8ae3-d3e1ae1c265d.png">


You will be able to install the development version once PR #269 has been merged via:
```
pip install git+https://github.com/creme-ml/creme.
```

**Comment by MaxHalford** [comment]
Ok we're done!

![dtree_draw png](https://user-images.githubusercontent.com/8095957/77251382-50f98480-6c4e-11ea-9527-6fc5a4f0d5e2.png)
