### ISSUE TITLE
Error with DecisionTreeClassifier.draw()

### ISSUE THREAD

**Issue by rmahesh123** [creme-ml/creme#272]
Hello,

Edit: This is a multi class classification problem. 

When trying to use this functionality (after installing latest development version), I am faced with the following error:

![image](https://user-images.githubusercontent.com/29958932/77343802-47c8f000-6d00-11ea-8442-3558ad0e5a04.png)

Here is the associated code:

```py
df = pd.read_csv(data)
 
target = df['Target']
del df['Target']
X = df.to_dict(orient='records')
 
model = tree.DecisionTreeClassifier()
metric = metrics.MicroF1()
 
for xi, yi in zip(X, target.values):
      y_pred = model.predict_one(xi)
      model.fit_one(xi, yi)
      metric.update(yi, y_pred)
      print(metric)
 
#Draw Decision Tree
model.draw(max_depth=3)
```

Any help would be much appreciated!

**Comment by raphaelsty** [comment]
@MaxHalford I think the error occurs when the tree consists of only one leaf.

What would be the effect of setting the default value of the ```depth``` parameter of the ```iter_dfs``` method to 0?

```python
class Leaf(Node):

    def path(self, x):
        yield self

    @property
    def size(self):
        return 1

    @property
    def height(self):
        return 0

    def iter_dfs(self, depth):
        yield self, depth

    def iter_edges(self):
        yield None, 0, None, self, 0
```

**Comment by raphaelsty** [comment]
@rmahesh123 I think you could avoid this error by having a tree with several leaves. To do this you can increase the value of the ```confidence``` parameter set to 1e-10 by default (1e-5 for example) and potentially decrease the value of the ```min_child_samples``` parameter set to 20 by default.

```python
model = tree.DecisionTreeClassifier(confidence=1e-5, min_child_samples = 5)
```

Still to solve this error and draw a leaf if there is only one.

**Comment by rmahesh123** [comment]
@raphaelsty  Thanks for the quick response! Unfortunately, that did work and I received the same error message as before.

**Comment by raphaelsty** [comment]
I managed to reproduce the error by reducing the confidence parameter:

```python
from creme import datasets
from creme import tree


model = tree.DecisionTreeClassifier(
    confidence=1e-40,
)

for x, y in datasets.Phishing():
    model.fit_one(x, y)
    
model.draw(3)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-c9cdea913b28> in <module>
     10 
     11     model.fit_one(x, y)
---> 12 model.draw(3)

~/Documents/github/creme/creme/tree/decision/tree.py in draw(self, max_depth)
    113         n_classes = len(set(itertools.chain(*[
    114             list(node.target_dist.keys())
--> 115             for node, _ in self.root.iter_dfs()])
    116         ))
    117 

TypeError: iter_dfs() missing 1 required positional argument: 'depth'
```

```python
from creme import datasets
from creme import tree

model = tree.DecisionTreeClassifier(
    confidence=0.5,
)

for x, y in datasets.Phishing():
    model.fit_one(x, y)
    
model.draw(2)
```

<img width="773" alt="image" src="https://user-images.githubusercontent.com/24591024/77347739-985c3f80-6d38-11ea-8fef-f9cc33380061.png">

**Comment by rmahesh123** [comment]
@raphaelsty Thanks for the response. I have tried lowering the confidence value but am still seeing the same error on my end. In an edit, I included that this is a multi class classification problem. Perhaps that may be the issue with model.draw()?

**Comment by raphaelsty** [comment]
@rmahesh123 I don't think it's a multi-class problem. I've opened a pull request that solves the problem on my side. #274 

In my opinion your tree is composed of a single leaf. Your model doesn't consider it useful to increase its depth. There can be multiple reasons for this, the distribution of the dataset, the number of observations and the parameters of your model.  

I recommend that you increase the "confidence" parameter again to 1, reduce the "min_child_samples" parameter again until @MaxHalford validate and update / merge the hot fix.

**Comment by rmahesh123** [comment]
@raphaelsty Thanks for the response. I will give this a try on my end and will be on the lookout for Max's update for #274

**Comment by MaxHalford** [comment]
Okay I merged the hot fix, it was a silly mistake.
