### ISSUE TITLE
Error with SuccessiveHalvingClassifier

### ISSUE THREAD

**Issue by rmahesh123** [creme-ml/creme#273]
Hello,

I started by installing the latest development version. I am working on a multi class classification problem. I am facing the following error on my end:

![image](https://user-images.githubusercontent.com/29958932/77345886-40efac80-6d03-11ea-9c4c-2329850ab1da.png)

Here is the following code I ran:

```py
df = pd.read_csv(data)

target = df['Target']
del df['Target']
X = df.to_dict(orient='records')

model = tree.DecisionTreeClassifier(max_depth=10)
metric = metrics.MicroF1()

for xi, yi in zip(X, target.values):
    y_pred = model.predict_one(xi) 
    model.fit_one(xi, yi) 
    metric.update(yi, y_pred) 

param_grid = {
            'DecisionTreeClassifier': {
            'max_depth': [1,2,3,4,5,6,7,8,9,10]}}

models = [model.set_params(**params) for params in param_grid]

sh = model_selection.SuccessiveHalvingClassifier(
        model=models,
        param_grid=param_grid,
        metric=metrics.MicroF1(),
        budget=20,
        eta=2)

model_selection.progressive_val_score(
   X_y = zip(X, target.values),
   model = sh,
   metrics=metrics.MicroF1()
   )

sh.best_model
```

Any help would be much appreciated!

**Comment by MaxHalford** [comment]
To solve the error you need to call `_set_params` and not `set_params`. For the moment this is a private method and therefore it starts with a `_`. Sorry for the confusion!

**Comment by MaxHalford** [comment]
Also, you're not using a pipeline so you can specify the parameters grid as so:

```py
param_grid = {
    'max_depth': [1,2,3,4,5,6,7,8,9,10]
}
```

**Comment by rmahesh123** [comment]
Hey Max,

Thanks for the suggestion. Below is what I am running:

`
df = pd.read_csv(data)

target = df['Target']
del df['Target']
X = df.to_dict(orient='records')

model = tree.DecisionTreeClassifier(max_depth=10)
metric = metrics.MicroF1()

for xi, yi in zip(X, target.values):
    y_pred = model.predict_one(xi) 
    model.fit_one(xi, yi) 
    metric.update(yi, y_pred) 

param_grid = {
    'max_depth': [1,2,3,4,5,6,7,8,9,10]
}

models = [
    model._set_params(**params)
    for params in model_selection.expand_param_grid(param_grid)
]

sh = model_selection.SuccessiveHalvingClassifier(
        model=models,
        param_grid=param_grid,
        metric=metrics.MicroF1(),
        budget=20,
        eta=2)

model_selection.progressive_val_score(
   X_y = zip(X, target.values),
   model = sh,
   metrics=metrics.MicroF1()
   )

sh.best_model
`
It is throwing the following error:
<img width="1123" alt="Screen Shot 2020-03-24 at 10 09 09 AM" src="https://user-images.githubusercontent.com/29958932/77441552-8e2d5600-6db7-11ea-82c2-fcafb3ef2a0e.png">

**Comment by MaxHalford** [comment]
Ok I just pushed a fix! You found a nice edge case :). I'm going to be adding some unit tests so that this kind of issue never happens again.

**Comment by rmahesh123** [comment]
@MaxHalford Thanks for getting back! Let me go ahead and give it another shot with your latest fix.

**Comment by rmahesh123** [comment]
@MaxHalford Hey Max. Just downloaded latest Creme version and I am facing the same error as before. Just wanted to let you know.

**Comment by MaxHalford** [comment]
Hey @rmahesh123. Are you sure you've installed the latest **development** version? Also you might have to remove the `**` in front of `**params`. I've been changing a few things internally. I'm probably going to be releasing a new stable version in the next few days anyway. Sorry you have to be the guinea pig!

I just ran the following snippet against the latest development version and nothing went wrong:

```py
from creme import datasets
from creme import tree
from creme import metrics
from creme import model_selection

model = tree.DecisionTreeClassifier()

param_grid = model_selection.expand_param_grid({
    'max_depth': [1, 2, 3, 4, 5, 6]
})

models = [model._set_params(params) for params in param_grid]

sh = model_selection.SuccessiveHalvingClassifier(
    models=models,
    metric=metrics.MicroF1(),
    budget=2000,
    eta=2,
    verbose=True
)

model_selection.progressive_val_score(
    X_y=datasets.Phishing(),
    model=sh,
    metric=metrics.MicroF1()
)
```

**Comment by rmahesh123** [comment]
@MaxHalford Thanks for getting back Max, happy to help out as these new features are released! I tried downloading the latest version as well. I will be on the lookout for the latest stable version in the next couple days.

**Comment by MaxHalford** [comment]
It would help if you could confirm that development version is working as you want it too. Then I can release a stable version that everyone can trust :).

**Comment by rmahesh123** [comment]
Hello Max. Sure thing happy to help :). I just downloaded the latest dev version and I am getting the same error as earlier when utilizing **params. When removing ** from **params, I am getting the error attached below:

<img width="761" alt="Screen Shot 2020-03-27 at 11 34 19 AM" src="https://user-images.githubusercontent.com/29958932/77778485-0ea1c000-701f-11ea-8b30-0bfec9534269.png">

**Comment by MaxHalford** [comment]
Are you your `param_grid` is correct? The example I gave [above](https://github.com/creme-ml/creme/issues/273#issuecomment-603963813) is definitely working.

**Comment by rmahesh123** [comment]
Hey Max. I ran the following on my end and I received the same error. Here is my code:

' ' ' 
from creme import datasets
from creme import tree
from creme import metrics
from creme import model_selection

df = pd.read_csv(data)

target = df['Target']

del df['Target']

X = df.to_dict(orient='records')

model = tree.DecisionTreeClassifier()

param_grid = model_selection.expand_param_grid({
    'max_depth': [1, 2, 3, 4, 5, 6]
})

models = [model._set_params(params) for params in param_grid]

sh = model_selection.SuccessiveHalvingClassifier(
    models=models,
    metric=metrics.MicroF1(),
    budget=2000,
    eta=2,
    verbose=True
)

model_selection.progressive_val_score(
    X_y=zip(X, target.values),
    model=sh,
    metric=metrics.MicroF1()
)
' ' ' 
Please let me know if I am missing anything on my end!

**Comment by MaxHalford** [comment]
That's really weird... Just to make sure, can you try running `pip install git+https://github.com/creme-ml/creme --upgrade` (note the `--upgrade`) and try again? I really think that this is because you don't have the latest development version.

**Comment by MaxHalford** [comment]
So I just checked again with @raphaelsty and @AdilZouitine and it seems to be working correctly for them too (altough Raphaël has the same issue as you before, weird...).

We created a new environment:

```sh
conda create -n test python=3.7
conda activate test
```

Then we did:

```sh
pip install cython
pip install git+https://github.com/creme-ml/creme
```

And finally we ran the following Python code:

```py
from creme import model_selection
from creme import tree

model = tree.DecisionTreeClassifier()

param_grid = model_selection.expand_param_grid({
    'max_depth': [1, 2, 3, 4, 5, 6]
})

models = [model._set_params(params) for params in param_grid]
```
