### ISSUE TITLE
.predict_proba_one(x) outputs 0.0 or 1.0 only

### ISSUE THREAD

**Issue by angulartist** [creme-ml/creme#286]
Hello

It seems like the predict_proba_one(x) function outputs 0.0 or 1.0 only. I expected something like 0.231 / 0.769 for example.

I'm just iterating over a test dataset with a trained LogisticRegression model (85% acc):

```python
for x, y in X_y_test:
    y_hat = model.predict_one(x)
    # Proba ?
    print(f"Game: {x['gameId']} - Frame #{x['frame']} - Target: {y} - Predict: {model.predict_proba_one(x)}")

    model.fit_one(x, y)
    metric.update(y_true=y, y_pred=y_hat)
```

I printed the raw dot funtion output in the predict_proba_one() function declared in glm.py and I got :

```bash
Raw dot: -192297.15713266327
Raw dot: -192297.15779714053
Game: 4546233126 - Frame #10 - Target: 1 - Predict: {False: 1.0, True: 0.0}
Raw dot: -620884.1535309438
Raw dot: -620884.154215456
Game: 4546233126 - Frame #12 - Target: 1 - Predict: {False: 1.0, True: 0.0}
Raw dot: 759206.0904690841
Raw dot: 759206.0907415837
Game: 4546233126 - Frame #14 - Target: 1 - Predict: {False: 0.0, True: 1.0}
Raw dot: 546562.0410140164
Raw dot: 546562.0412863821
Game: 4546233126 - Frame #16 - Target: 1 - Predict: {False: 0.0, True: 1.0}
Raw dot: 1205742.3135586819
Raw dot: 1205742.3138309137
Game: 4546233126 - Frame #18 - Target: 1 - Predict: {False: 0.0, True: 1.0}
Raw dot: 2242763.38610308
Raw dot: 2242763.386375178
Game: 4546233126 - Frame #20 - Target: 1 - Predict: {False: 0.0, True: 1.0}
```

I feel like the values are pretty big. My model should not be that confident.

Is it normal behaviour?

Thanks

**Comment by MaxHalford** [comment]
Hey there. Alas I can't give you an answer without taking a look at the data.

**Comment by angulartist** [comment]
> Hey there. Alas I can't give you an answer without taking a look at the data.

Here is the dataset I'm using : https://www.kaggle.com/bobbyscience/league-of-legends-soloq-ranked-games

**Comment by MaxHalford** [comment]
I just took a quick look at your model:

```py
model = compose.Discard('gameId', 'frame')
model |= compose.Discard('isFirstTower', 'isFirstBlood') + preprocessing.StandardScaler()
model |= linear_model.LogisticRegression(opt)
```

Are you sure it's doing what you want? The second line means that you're making two copies of your features, one without `isFirstTower` and `isFirstBlood`, and one where all the features scaled. Maybe what you rather want to do is:

```py
model = compose.Discard('gameId', 'frame')
model |= compose.Discard('isFirstTower', 'isFirstBlood')
model |= preprocessing.StandardScaler()
model |= linear_model.LogisticRegression(opt)
```

If not I'll take a deeper look :)

**Comment by angulartist** [comment]
@MaxHalford WOW nice catch, problem resolved I'm getting the proba! 😮 

Well, I'm still discovering the pipeline composing stuff. The way I did that is because I wanted to Scale the numerical attributes and to One-Hot encode the categorical attributes.

I know how to do that with sklearn using the ColumnTransformer pipeline but not with Creme 😢 

Thanks!

**Comment by MaxHalford** [comment]
Actually that's something we were talking about with the team @creme-ml/developers at some point... I believe that a good idea would be to implement a `SelectType` transformer. This would allow to select features based on their type. It would look like this:

```py
from creme import base

class SelectType(base.Tranformer):
    
    def __init__(self, dtype):
        self.dtype = dtype
    
    def transform_one(self, x):
        return {i: xi if isinstance(xi, self.dtype)}
```

This would allow doing the following:

```py
import numbers

from creme import linear_model
from creme import preprocessing

num = SelectType(numbers.Number) | preprocessing.StandardScaler()
cat = SelectType(str) | preprocessing.OneHotEncoder()
model = (num + cat) | linear_model.LogisticRegression()
```

Tell me if I've missed something. We can discuss specific details. It's always great to be able to add features that make a user's life easier.

**Comment by angulartist** [comment]
That would be a great feature! I think it will be easier if we can just pass a list of attributes just like for .Discard() and .Select() so we do not depend on the type. 😄 
Thanks a lot!

**Comment by MaxHalford** [comment]
> I think it will be easier if we can just pass a list of attributes just like for .Discard() and .Select() so we do not depend on the type.

Can you elaborate on this?

**Comment by angulartist** [comment]
Let's say we have extracted numerical and categorial feature column names.

```python
num = ['numTowers', 'numKills', 'numDeaths', 'numDragons']
cat   = ['isFirstBlood', 'isFirstTower', 'gameType']
```

Now the user wants to normalize numerical attributes and one-hot encode the categorical ones.

```pyhton
num = SelectFilter(num_attrs) | preprocessing.Normalize()
cat   = SelectFilter(cat_attrs) | preprocessing.OneHotEncoder()

model = (num + cat) | linear_model.LogisticRegression()
```

Or simply :

```python
num = SelectFilter('numKills', 'numDeaths') | preprocessing.Normalize()
cat   = SelectFilter('isFirstBlood') | preprocessing.OneHotEncoder()

model = (num + cat) | linear_model.LogisticRegression()
```

**Comment by MaxHalford** [comment]
But isn't that what `compose.Select` already does?

**Comment by angulartist** [comment]
You're right XD After writing it, I was like, I saw this somewhere 😭 

Well, I really need to improve my pipeline skills then, I think ive missed the point.

**Comment by MaxHalford** [comment]
No worries :)

**Comment by angulartist** [comment]
I close the issue because it's resolved for me.
