### ISSUE TITLE
module 'creme' has no attribute 'preprocessing'

### ISSUE THREAD

**Issue by RP-23** [creme-ml/creme#287]
Hi all,
First of all, thank you for this amazing library.

I'm trying to use the MinMaxScaler preprocessing, but I'm getting the error - module 'creme' has no attribute 'preprocessing'. I'm simply trying to replicate the example in [https://creme-ml.github.io/content/generated/creme.preprocessing.MinMaxScaler.html#creme.preprocessing.MinMaxScaler]

Can anyone help me on this?

**Comment by raphaelsty** [comment]
Hi @RP-23, to import MinMaxScaler I do:

```python
from creme import preprocessing

scaler = preprocessing.MinMaxScaler()
``

**Comment by raphaelsty** [comment]
I do not have any issue with the example you quoted, it's weird...

**Comment by RP-23** [comment]
Yes, that worked for me! Thanks @raphaelsty

**Comment by raphaelsty** [comment]
Nice @RP-23, have a good day.

**Comment by MaxHalford** [comment]
Actually the issue was valid. You can't import `creme` and access `creme.preprocessing.StandardScaler`. We need to fix the example in the docstring of `StandardScaler`.
