### ISSUE TITLE
Stream QA - Boolean 

### ISSUE THREAD

**Issue by raphaelsty** [creme-ml/creme#288]
When using ``stream.simulate_qa`` it is essential to verify that the target ``y``is equal or different from ``None``. I think it would be useful to add a boolean field to prevent the user from encountering the following side effect:

```python
>>> X_y = stream.simulate_qa(
... X_y=stream.iter_csv('./dataset.csv', **params), 
... moment='date', 
... delay=datetime.timedelta(days=7)
... )

>>> for i, x, y in X_y:
...     if y:
...     # Fit model
...     else:
...     # Predict
```

Everything is fine in the above code, unless it is strictly equal to "0" or "0.0". If y is equal to 0 then the model makes a prediction. The value 0 behaves as ``None`` in the condition `ìf``.

```python
>>> if 0:
...    print(0)
...  else:
...    print(1) # Will print 1.
1

>>> if None:
...    print(0)
...  else:
...    print(1) # Will print 1.
1

>>> if 0 != None:
...    print(0) # Will print 0.
...  else:
...    print(1) 
0
```

Currently, this is what all users of stream.simulate_qa should be doing:

```python
>>> X_y = stream.simulate_qa(
... X_y=stream.iter_csv('./dataset.csv', **params), 
... moment='date', 
... delay=datetime.timedelta(days=7)
... )

>>> for i, x, y in X_y:
...     if y != None:
...     # Fit model
...     else:
...     # Predict
```

[qa.py](https://github.com/creme-ml/creme/blob/master/creme/stream/qa.py)

I will find it convenient to add a boolean to the generator to avoid this side-effect. We could replace the variable "i" with this indicator for example.

**Comment by MaxHalford** [comment]
Mmm I'm not sure about this. I would rather improve the documentation and explain that `y` being `None` implies a prediction has to be made. In any case, `simulate_qa` is a lower-level function than `progressive_val_score` which takes of this anyway.

**Comment by raphaelsty** [comment]
Indeed, I have just understood the role of variable i, which is very practical.

I will be careful to verify that my variable is different from None in the future. ;-)
