### ISSUE TITLE
Separate grouping logic

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#293]
We now have quite a few transformers that have a `by` parameter to apply transformations within groups, for instance:

- `feature_extraction.Agg`
- `feature_extraction.TargetAgg`
- `feature_extraction.Differ`
- `impute.StatImputer`

I'm thinking that it might be a good idea to put the logic of grouping data in a separate transformer. If we overload another operator, say `@`, then we could do the following:

```py
agg = feature_extraction.Agg(on='x', how=stats.Mean()) @ ('foo', 'bar')
```

instead of:

```py
agg = feature_extraction.Agg(on='x', how=stats.Mean(), by=['foo', 'bar'])
```

The advantage is that each estimator doesn't have to handle the grouping logic by itself. This would simplify existing implementations and remove some repetitive code. Another advantage is that we could then do grouping with every estimator, which adds a lot of room for creativity and expressiveness. The disadvantage is users have to be familiar with this operator, but I don't think that's a bad thing, seeing that we're committing to using operator overloading anyway.

@creme-ml/developers what do you think?

**Comment by gbolmier** [comment]
Do you mean overloading `base.Transformer` with something like:

```python
def __matmul__(self, by):
    self.by = by if isinstance(by, (typing.List, typing.Tuple)) else [by]
    return self
```

**Comment by MaxHalford** [comment]
Nope. I mean that the operator would create a new transformer that contains the grouping logic. For instance it could be called `GroupTransformer`. It's responsibility would be to store one transformer for each value of the `by` attribute. In other words, `feature_extraction.Agg` would not have to worry about taking care of grouping because that would be handled in `GroupTransformer`.

**Comment by gbolmier** [comment]
Thanks for elaborating Max, that's interesting, would definitely be a helpful abstraction on our side :+1: 

On the user side I'm more troubled, I think it makes things more complex by decomposing the abstraction (it requires to create and assemble two objects instead of one). I'm worried it would open the door to usage mistakes and decrease readability

**Comment by MaxHalford** [comment]
Yeah I agree. Note that users can also use the following syntax:

```py
agg = GroupTransformer(
    estimator=feature_extraction.Agg(on='x', how=stats.Mean()),
    by=['foo', 'bar']
)
```

I guess we need more input from other people :)

**Comment by raphaelsty** [comment]
I think it's a great idea.

**Comment by gbolmier** [comment]
Yep would be nice to hear more opinions! We could also just separate the grouping logic in the internal api by inheriting from a `GroupTransformer` class

**Comment by MaxHalford** [comment]
I've implemented something [here](https://creme-ml.github.io/api-reference/compose/Grouper/).
