### ISSUE TITLE
Get feature importance with naive bayes Creme

### ISSUE THREAD

**Issue by zakaria47fs** [creme-ml/creme#298]
Hi,
Is there a way to get feature importance and the top features/words for each class after fitting Creme Naive Bayes model ? something like : NB_model.coefs_ or NB_model.feature_log_prob_ on Scikit-learn,

**Comment by MaxHalford** [comment]
Hello.

At the moment you can access the `feature_counts` field to see the class distribution for each each feature. This isn't exactly what you're looking for, but it can be manipulated to reach what you want. We could implement something to make it easier to interpret; a pull request would be welcome :)
