### ISSUE TITLE
Incremental PCA implementation

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#3]
Incremental PCA is already [implemented in scikit-learn](https://scikit-learn.org/stable/auto_examples/decomposition/plot_incremental_pca.html) but seems like it is straightforward to implement. See [this paper](http://cs-www.cs.yale.edu/homes/el327/papers/opca.pdf) too.

**Comment by tweakyllama** [comment]
I'd like to work on this if that's alright

**Comment by MaxHalford** [comment]
You're on! Feel free to ask questions :). One thing to note is that this new `PCA` class will be part of a new module called `decomposition`.

I'm just about to review your PR for `AdaBound` :). We're also going to be adding a nice of contributors to the `README.md` to give your help some exposure.

**Comment by tweakyllama** [comment]
Cheers, yeah will do.

**Comment by MaxHalford** [comment]
Any progress @lbowenwest? If not I'll do it.

**Comment by MaxHalford** [comment]
[This paper](https://arxiv.org/abs/1307.0032) looks quite promising.

**Comment by MaxHalford** [comment]
Added to the [icebox](https://github.com/creme-ml/creme/projects/2).

**Comment by microprediction** [comment]
Did this make it in?

**Comment by gbolmier** [comment]
No, there is some ongoing (or stale?) work in #1509 that apparently requires reviewing time.

**Comment by microprediction** [comment]
Thx!
