### ISSUE TITLE
Mode - The value that appears most often

### ISSUE THREAD

**Issue by raphaelsty** [creme-ml/creme#30]
Implement mode, this new feature will use creme.stats.Count() and unique().

It could be useful to impute categorical features.

Related to issues #16 #24

**Comment by raphaelsty** [comment]
@AdilZouitine @MaxHalford What about an incremental CountVectorizer, could it be an issue too?

**Comment by MaxHalford** [comment]
For sure the mode is a useful stat. Just like the number of unique values I think we should use a sketch/bloom filter to get an approximation without requiring too much memory.

As for the CountVectorizer it's already implemented in the `feature_extraction` module.
