### ISSUE TITLE
predict_many bug?

### ISSUE THREAD

**Issue by deklanw** [creme-ml/creme#304]
`creme==0.6.1`

`predict_one`, `fit_one`, and `progressive_val_score` are working fine here. I just get a problem with `predict_many`

```python
    m = multiclass.OneVsRestClassifier(
        classifier=linear_model.LogisticRegression())

    model = compose.Select(
        *numerical_features) | preprocessing.StandardScaler()

    model += compose.Select(*
                            categorical_features) | preprocessing.OneHotEncoder(sparse=True)
    model |= m

...

    predictions = model.predict_many(champ_data)

```

Stack trace:

```
  File "./server.py", line 89, in predict_10_batch
    predictions = model.predict_many(champ_data)
  File "/home/deklan/.local/share/virtualenvs/server-M2NtlTFu/lib/python3.8/site-packages/creme/compose/pipeline.py", line 556, in predict_many
    X, final_step = self._transform_many(X=X)
  File "/home/deklan/.local/share/virtualenvs/server-M2NtlTFu/lib/python3.8/site-packages/creme/compose/pipeline.py", line 533, in _transform_many
    sub_t.fit_many(X=X)
TypeError: fit_many() missing 1 required positional argument: 'y'
```

**Comment by MaxHalford** [comment]
Hey there, I found some quirks too. However, the main issue with your pipeline is that you're using features that don't support mini-batches yet. In fact, only `StandardScaler`, `LinearRegression`, and `LogisticRegression` have support for them.

**Comment by deklanw** [comment]
Oh, I see. I didn't realize support was limited. My batches are only 10 samples large. I was just testing to see if it performed a bit better than looping thru the 10 (probably not, anyway).

**Comment by MaxHalford** [comment]
Yes we're still in early stages in regards to mini-batches :). Although I suppose every estimator you have in your pipeline is worthy of being upgraded to mini-batches, so there's a high chance that that will happen in the near future. As always, pull requests are welcome!
