### ISSUE TITLE
Bibtex citation

### ISSUE THREAD

**Issue by jklaise** [creme-ml/creme#305]
I would like to cite `creme` in a paper but not sure what the appropriate format would be, especially with respect to authors. This would be very useful for anyone using `creme` in academic work.

**Comment by MaxHalford** [comment]
Hey! That's a good suggestion. I'll try to get something done during the day :)

**Comment by MaxHalford** [comment]
Ok so I've added an entry to Google Scholar, it should appear soon if you search for "creme, a Python library for online machine learning".

Just curious, what's the publication? :)

**Comment by jklaise** [comment]
Thanks, it's come up on google scholar, although I had to write a bibtex entry myself, maybe it's worth putting it on the Github readme too? Here's my attempt (disclaimer: for bibtex @software isn't always standard and some people use @misc instead, I'm still not 100% sure what the right style and fields are for software):

```
@software{creme,
  title = {{creme}, a {P}ython library for online machine learning},
  author = {Bolmier, Geoffrey and Halford, Max and Sourty, Raphael and Vaysse, Robin and Zouitine, Adil},
  url = {https://github.com/creme-ml/creme},
  version = {0.6.1},
  date = {2020-06-10},
  year = {2019}
}
```

The paper in question is for [this ICML workshop](https://sites.google.com/view/deploymonitormlsystems/home) on model deployment and monitoring, I though `creme` deserves a shoutout for providing an implementation of streaming metrics and histograms!

**Comment by MaxHalford** [comment]
Cheers for that! I don't have a lot of publishing experience so I was also wondering between @software and @misc. I'll add the entry you propose to the README :). Thank you very much for the shoutout, and good look with your publication.
