### ISSUE TITLE
AttributeError: 'Leaf' object has no attribute 'Leaf'

### ISSUE THREAD

**Issue by abhibha1807** [creme-ml/creme#306]
Hey,
I am trying to code a POS Tagger on the Conll dataset. I am currently experimenting with different classifiers one of them being the DecisionTree Classifier. I coded by own pipeline for preprocessing the data and ran 'model.debug()' to understand the flow but I seem to getting the following error.
>Traceback (most recent call last):
  File "decisiontree_classifier_conll_creme.py", line 175, in <module>
    main()
  File "decisiontree_classifier_conll_creme.py", line 166, in main
    report = model.debug_one(X_y[0][0])
  File "/Users/abhibhagupta/anaconda3/lib/python3.7/site-packages/creme/compose/pipeline.py", line 458, in debug_one
    _print(final.debug_one(x))
  File "/Users/abhibhagupta/anaconda3/lib/python3.7/site-packages/creme/tree/decision/tree.py", line 165, in debug_one
    if isinstance(node, node.Leaf):
AttributeError: 'Leaf' object has no attribute 'Leaf' 

I have attached the code and the dataset [github.zip](https://github.com/creme-ml/creme/files/4798284/github.zip). Thank you :D

**Comment by VaysseRobin** [comment]
Ok, I see the problem. In the file `creme.tree.decision.tree.py` we imported a module called `node` which contain some types usefull for trees. But in tree.py, we overwrote the name `node` several times by using variables called `node`. So we just need to rename the variables `node` in the `tree.py` file and it should work. I will make a fix but we will have to wait for @MaxHalford to merge it.

**Comment by raphaelsty** [comment]
@VaysseRobin Nice catch, could you reproduce the error and show how your hot fix solve it? :-)

**Comment by MaxHalford** [comment]
Ok it's been merged. A unit test should probably added to check the `debug_one` method of decision trees works.

**Comment by abhibha1807** [comment]
It works! thank you :)
