### ISSUE TITLE
`AttributeError: module `creme.base` has no attribute `typing`.

### ISSUE THREAD

**Issue by landmann** [creme-ml/creme#308]
What gives?

![image](https://user-images.githubusercontent.com/12756081/85255822-99b31a80-b495-11ea-80d5-1e47110a2d1b.png)

**Comment by VaysseRobin** [comment]
Could you please provide the code to reproduce the error and also the `creme` version you are using ?

**Comment by landmann** [comment]
It's a simple `from creme import metrics` that gives me this error. My version is 0.6.1.

**Comment by MaxHalford** [comment]
Also, what version of Python are you using?

**Comment by landmann** [comment]
Thanks so much guys - I am using Arch Linux, python 3.7.7

**Comment by landmann** [comment]
Wow - kidding. A day later and now it works. Sorry for the hassle guys.
