### ISSUE TITLE
Rolling statistics

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#31]
At the moment we compute running statistics and that's fine. It would be nice to also have running rolling statistics. For example we might want to compute the mean inside a window of values. I'm not sure if any smart way to do this exists. But I think this is important if we want our models to capture potential drifts.

**Comment by raphaelsty** [comment]
RollingStatistics:
"""Compute rollings statistics with a given windows size

Attributes:
       on (str): target variable
       n (int): size of the window
       by (str): aggregate
       how (str): tools to use, reference creme.stats object
"""     
Idea : 
This class would take the last n value to compute a mean or any other statistics.

**Comment by MaxHalford** [comment]
Yep @raphaelsty that's the idea. The trick is that I'm not sure how do this effectively without having to recompute the mean/std every time...

**Comment by raphaelsty** [comment]
@MaxHalford I'd like to try to solve this issue :-)

**Comment by MaxHalford** [comment]
Rock on :+1:
