### ISSUE TITLE
Custom sklearn + LightGBM model 

### ISSUE THREAD

**Issue by luistelmocosta** [creme-ml/creme#313]
Hello, I have a custom sklearn + lightgbm model and I would like to know if it is possible to include this model in a creme pipeline. If not, is there any way to do text classification with LightGBM in a creme pipeline?

Kind Regards,
Luís

**Comment by MaxHalford** [comment]
Hey @luistelmocosta! Alas LightGBM is a batch, and therefore cannot be trained incrementally. In particular it doesn't have a `partial_fit` method.

**Comment by luistelmocosta** [comment]
Thank you for your reply! Is there any text classification pipeline for Creme?

**Comment by MaxHalford** [comment]
Well for instance you can use the [TFIDF](https://creme-ml.github.io/api-reference/feature-extraction/TFIDF/) and then chain that with a [LogisticRegression](https://creme-ml.github.io/api-reference/linear-model/LogisticRegression/).
