### ISSUE TITLE
Hello, the API manual cannot be opened normally. Thank you very much

### ISSUE THREAD

**Issue by hundredupset** [creme-ml/creme#326]
## Versions

**`creme` version** : 

**Python version** : 

**Operating System** :

## Steps/Code to Reproduce

```python
# Sample code to reproduce the problem
```

**Comment by MaxHalford** [comment]
Hello @hundredupset, can you be more precise? The [API reference page](https://creme-ml.github.io/api-reference/overview/) seems to be working.

**Comment by hundredupset** [comment]
> Hello @hundredupset, can you be more precise? The [API reference page](https://creme-ml.github.io/api-reference/overview/) seems to be working.
![problem](https://user-images.githubusercontent.com/32949869/89727776-55d29f80-da5a-11ea-9cf4-53d77eafbe2e.png)

**Comment by MaxHalford** [comment]
I can't read Mandarin/Cantone so I can't help you out on that. I guess that the lower left button allows performing a one-time exception. The documentation is hosted on GitHub Pages so it's a bit weird that your browser doesn't trust it.
