### ISSUE TITLE
Online LDA

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#33]
Latent Dirichlet Allocation is a cool model and there is a nice online algorithm to learn it's parameters. 

References:

- [Online Learning for Latent Dirichlet Allocation](https://www.di.ens.fr/~fbach/mdhnips2010.pdf)
- [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.LatentDirichletAllocation.html)
- [Your Easy Guide to Latent Dirichlet Allocation](https://medium.com/@lettier/how-does-lda-work-ill-explain-using-emoji-108abf40fa7d)

**Comment by MaxHalford** [comment]
After having taken a look at this I believe that the papers I mentioned are not "truly" online because they assume the size of the vocabulary is known before-hand, which is a big no no for `creme`. However I found [this](http://proceedings.mlr.press/v28/zhai13.pdf) approach which seems promising.

**Comment by raphaelsty** [comment]
I'd like to work on the issue :-)

**Comment by MaxHalford** [comment]
Stumbled on this paper: [Streaming-LDA: A Copula-based Approach to ModelingTopic Dependencies in Document Streams](https://hal.archives-ouvertes.fr/hal-01344779/document).

**Comment by MaxHalford** [comment]
Done! A round of applause for @raphaelsty!

**Comment by hans-ekbrand** [comment]
So, how do one use this feature, is it documented anywhere?

**Comment by MaxHalford** [comment]
At the moment there's only a little example [here](https://riverml.xyz/latest/api/preprocessing/LDA/).
