### ISSUE TITLE
Run a spell checker

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#344]
It would be nice to run [codespell](https://github.com/codespell-project/codespell) or something similar to correct possible spelling mistakes in the code.

**Comment by mihir-thakkar-ai** [comment]
> It would be nice to run [codespell](https://github.com/codespell-project/codespell) or something similar to correct possible spelling mistakes in the code.

Hi, is this issue still open? I would like to contribute.

**Comment by MaxHalford** [comment]
Knock yourself out 👍

**Comment by MaxHalford** [comment]
Actually, I just thought of something. If you do this, can do it on the the-merge branch?

**Comment by mihir-thakkar-ai** [comment]
Sure, I will do this on "the-merge" branch.

**Comment by MaxHalford** [comment]
Thanks a lot for doing this 💯
