### ISSUE TITLE
Balanced accuracy metric

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#360]
It would be nice to add the [balanced accuracy metric](https://scikit-learn.org/stable/modules/model_evaluation.html#balanced-accuracy-score) to the `metrics` module. This can implemented as the average of the recalls for each class.

**Comment by MaxHalford** [comment]
Hey @sinAshish, cool!

You would need to create a `BalancedAccuracy` class and add it to the `metrics` module in a dedicated file. You can use the `Accuracy` metric as a template. What's important is that you add unit tests in the docstring to check that the implementation is correct. You also need to add the class name to the `__all__` variable in the `metrics/__init__.py` file. That's it! The class will be automatically added to the documentation, you just have to worry about writing a nice docstring.

**Comment by sinAshish** [comment]
Okay.
I can use the `Accuracy` class to see how to implement `BinaryAccuracy`.

**Comment by MaxHalford** [comment]
You can look at `Accuracy` to get an idea of what the implementation should look like in terms of structure. You can look at the [scikit-learn implementation](https://scikit-learn.org/stable/modules/model_evaluation.html#balanced-accuracy-score) to understand the math behind the balanced accuracy metric.

**Comment by sinAshish** [comment]
should I compute the confusion matrix before calling the BalancedAccuracy(), and make the matrix as a parameter for the metric? because I'm not able to figure out how to handle the `.predict_one()`

**Comment by MaxHalford** [comment]
Actually now that I think about it, the `metrics` module has been revamped in the [`the-merge`](https://github.com/creme-ml/creme/tree/the-merge) branch. You can either look there, or wait a couple of weeks once we've merged it into master.

**Comment by sinAshish** [comment]
yes, there has been a complete revamp of the code. And even the confusion matrix is being shared here.
So should I work wrt the `the-merge` branch or the current master or just wait?

**Comment by MaxHalford** [comment]
Work on the-merge :). Indeed, the confusion matrix is shared. This has two benefits: 1) Computing multiple metrics is faster. 2) Using the confusion matrix eases the implementation of certain metrics.

**Comment by MaxHalford** [comment]
Thanks @sinAshish, I've merged your PR :))
