### ISSUE TITLE
GPU or Multiprocessing support

### ISSUE THREAD

**Issue by Aaryanverma** [creme-ml/creme#361]
While training the pipeline on a large dataset, it takes so long time because of super slow for loop on training object. Multiprocessing or GPU support for training should be introduced in the pipelines in order to make this process faster.

**Comment by MaxHalford** [comment]
Hey there, thanks for opening the issue.

Agreed, creme is rather slow at processing a large dataset. But processing a large dataset isn't what creme is meant for. creme is meant to process streams of data, where samples arrive 1 by 1. creme is much faster than any other Python library at this task.

The question is not how fast creme can process a dataset, but how fast creme can process a single observation. If your goal is to build a model on a large dataset, then I recommend that you use a batch model. If not, you can also use mini-batching in creme. Some models, such as `processing.StandardScaler` and `linear_model.LinearRegression`, have a `learn_many` method which takes as input a `pandas.DataFrame`.

What kind of multiprocessing are you thinking about? Creating processes brings a lot of overhead, which hinders our ability to process a single observation as fast as possible. If the goal is to process more data, then that's what mini-batching is for.

As for GPUs, that's not our ballpark. Our goal is to provide a lightweight solution that can be deployed on cheap servers as well as IoT devices.

**Comment by Aaryanverma** [comment]
okay, thanks for this info. I got my answer and closing this issue.
