### ISSUE TITLE
Error during  installation 

### ISSUE THREAD

**Issue by hashmiuk** [creme-ml/creme#381]
Hello 

Am getting the following error when am try to install creme in Jupiter notebook

pip install creme==0.6.1

ERROR: Command errored out with exit status 1:
   command: 'C:\Users\space\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\space\\AppData\\Local\\Temp\\pip-install-sf200tgc\\mmh3\\setup.py'"'"'; __file__='"'"'C:\\Users\\space\\AppData\\Local\\Temp\\pip-install-sf200tgc\\mmh3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\space\AppData\Local\Temp\pip-wheel-elu95ulh'
       cwd: C:\Users\space\AppData\Local\Temp\pip-install-sf200tgc\mmh3\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'mmh3' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for mmh3
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\space\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\space\\AppData\\Local\\Temp\\pip-install-sf200tgc\\mmh3\\setup.py'"'"'; __file__='"'"'C:\\Users\\space\\AppData\\Local\\Temp\\pip-install-sf200tgc\\mmh3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\space\AppData\Local\Temp\pip-record-9rja0348\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\space\anaconda3\Include\mmh3'
         cwd: C:\Users\space\AppData\Local\Temp\pip-install-sf200tgc\mmh3\
    Complete output (5 lines):
    running install
    running build
    running build_ext
    building 'mmh3' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\space\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\space\\AppData\\Local\\Temp\\pip-install-sf200tgc\\mmh3\\setup.py'"'"'; __file__='"'"'C:\\Users\\space\\AppData\\Local\\Temp\\pip-install-sf200tgc\\mmh3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\space\AppData\Local\Temp\pip-record-9rja0348\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\space\anaconda3\Include\mmh3' Check the logs for full command output.

**Comment by raphaelsty** [comment]
Hello,

Other people encounter this difficulty when installing Python libraries with Windows.

It looks like you have to download Microsoft C++ Build Tools:

https://stackoverflow.com/questions/64261546/python-cant-install-packages

Raphael :)

**Comment by MaxHalford** [comment]
Note that we've removed the dependency on mmh3 in the next release.

**Comment by hashmiuk** [comment]
> Hello,
> 
> Other people encounter this difficulty when installing Python libraries with Windows.
> 
> It looks like you have to download Microsoft C++ Build Tools:
> 
> https://stackoverflow.com/questions/64261546/python-cant-install-packages
> 
> Raphael :)

Thank you very much. It is working fine.
