### ISSUE TITLE
Standard error of the mean

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#46]
The standard error for the mean would be a nice statistic to have. Here are some references:

- [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html)
- [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.sem.html).

**Comment by AdilZouitine** [comment]
[Accurately computing running variance](https://www.johndcook.com/blog/standard_deviation/)

**Comment by raphaelsty** [comment]
#55 pending pending pull request

**Comment by MaxHalford** [comment]
Done!
