### ISSUE TITLE
Patsy formulation

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#49]
[patsy](https://patsy.readthedocs.io/en/latest/overview.html) is a library for formulating statistical models. I just watched this [great talk](https://www.youtube.com/watch?v=68ABAU_V8qI&feature=youtu.be) where at the 3rd minute the `X` and `y` are obtained via `patsy`'s `dmatrices` function. I think this is very elegant and reminiscent of R. I think that we could implement something like this in the `stream` module or the `feature_extraction` module. Needs some thinking about though.

**Comment by koaning** [comment]
I merely want to mention that this feature is now implemented in scikit-lego: https://scikit-lego.readthedocs.io/en/latest/preprocessing.html.

**Comment by MaxHalford** [comment]
Cheers @koaning!

**Comment by MaxHalford** [comment]
Looks like using [pyparsing](https://github.com/pyparsing/pyparsing/) could be a good approach.
