### ISSUE TITLE
Sphinx autosummary automation

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#59]
At the moment we're using the [autosummary](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html) of Sphinx to generate tables that contain the classes of each module. The problem is that we have to manually add new classes to each module's `.rst` file. This is error-prone and it would be better if all the classes of each module were automatically added. I've tried to do this yesterday, but to no avail :(

**Comment by mrshu** [comment]
@MaxHalford thanks for putting a ton of work into such a nice package!

I am wondering whether [automodsum](https://sphinx-automodapi.readthedocs.io/en/latest/automodsumm.html) may be of help here. It should be possible to point it at the specific module (say `creme.feature_selection` in case of [`feature_selection.rst`](https://github.com/creme-ml/creme/blob/master/docs/feature_selection.rst)) and everything else should be taken care of.

Do let me know if I can be of any help with regards to this.

Thanks!

**Comment by MaxHalford** [comment]
Hey @mrshu,

I'll take a look at this when I get back from vacation and see if it works. Thanks a lot, I didn't know about it.

Kind regards.

**Comment by MaxHalford** [comment]
I just tried `automodsum` but wasn't satisfied. It generates single page of documentation for each module and doesn't seem to allow generating one page per class. Maybe I missed something.

**Comment by MaxHalford** [comment]
Done. In the end I wrote my own script because it gave me more control.
