### ISSUE TITLE
L1 regularization for linear models

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#76]
Shouldn't be too difficult to do but I'm not sure how exactly to make it work with L2 regularization at the same time. L1 + L2 is called ElasticNet but I'm not sure of the details.

References:

- [Stochastic Gradient Descent Training forL1-regularized Log-linear Models with Cumulative Penalty](https://www.aclweb.org/anthology/P09-1054)
- [Sparse Online Learning via Truncated Gradient](http://hunch.net/~jl/projects/interactive/sparse_online/paper_sparseonline.pdf)

**Comment by gbolmier** [comment]
One more reference: [Efficient Learning using Forward-Backward Splitting](https://papers.nips.cc/paper/3793-efficient-learning-using-forward-backward-splitting)

**Comment by gbolmier** [comment]
Ran some [experiments](https://nbviewer.jupyter.org/github/gbolmier/workbench/blob/master/induce-sparsity-in-online-learning-linear-models.ipynb) implementing methods proposed here:

> * [Stochastic Gradient Descent Training forL1-regularized Log-linear Models with Cumulative Penalty](https://www.aclweb.org/anthology/P09-1054)
> * [Sparse Online Learning via Truncated Gradient](http://hunch.net/~jl/projects/interactive/sparse_online/paper_sparseonline.pdf)

We have pretty good results on a synthetic dataset of 10 informative features, and 90 noisy features:

| Method                | Hyper-parmameters                     | # of features | MAE |
|:----------------------|:--------------------------------------|--------------:|:---:|
| No regularization     |                                       |           100 | 8.2 |
| L1 naive              | λ = 0.1                       |           100 | 8,7 |
| L1 cumulative         | λ = 0.1                       |            11 | 6.7 |
| Truncated gradient    | λ = 5 &nbsp; K=10 &nbsp; θ = 3 |             9 | 6.8 |

![download](https://user-images.githubusercontent.com/25319692/89712714-e2b22600-d992-11ea-8c33-4b2e2af4248c.png)

**Comment by MaxHalford** [comment]
That looks really good Geoff! Let's wait till we've moved forward with the scikit-multiflow merge. The cost can probably be alleviated by writing some of it in Cython.
