### ISSUE TITLE
JSON serialization

### ISSUE THREAD

**Issue by MaxHalford** [creme-ml/creme#87]
In the long term it would be nice to be able to serialize any `creme` estimator to a JSON format. Pickle works okay but it isn't everyone's cup of tea. See [this post](https://cmry.github.io/notes/serialize) and [this other post](https://cmry.github.io/notes/serialize-sk) about the issues of serializing an `sklearn` estimator.

**Comment by ronnyli** [comment]
Hi I'm new to this library but it looks awesome! Just wondering if I should pickle both the model and metric objects if I intend to continue the training process at a later time? Thanks in advance

**Comment by ronnyli** [comment]
hm on that note I'm receiving this error when trying to save the model
```
AttributeError: Can't pickle local object 'compose.<locals>.compose2.<locals>.<lambda>'
```
Code:
```
....
model = compose.Pipeline([
    ('tfv', tfv),  # TFIDFVectorizer
    ('lin_reg', lr)  # LinearRegression
])

metric = metrics.MSE()
....
with open('model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)
```

**Comment by MaxHalford** [comment]
Hey @ronnyli,

Indeed you need to pickle your metric if you want to keep track of it later on.

As for the error you got, it's a bug and I'll get it fixed right away. It's due to the fact that `TFIDFVectorizer` has a `lambda` function somewhere in it's properties, and `lambda` functions can't be pickled.

**Comment by MaxHalford** [comment]
After some discussions it seems that `pickle` is more than fine for now. I'm closing this for now as there are many things to be done.
