### ISSUE TITLE
FBeta score metric

### ISSUE THREAD

**Issue by gbolmier** [creme-ml/creme#88]
F1 score is a particular case of FBeta score where precision and recall and equivalently weighted by setting beta to 1. It would be easy to implement a `FBetaScore` in the `metric` module as the `F1Score` have been already done. It would be nice to also support different beta values for each different class.

**Comment by MaxHalford** [comment]
@gbolmier you can do `RollingFBetaScore` too :)

**Comment by gbolmier** [comment]
With pleasure @MaxHalford :+1:
