### ISSUE TITLE
EWVariance

### ISSUE THREAD

**Issue by koaning** [creme-ml/creme#93]
If you have the variance and the mean over time then these two lego-bricks can combine into a pretty reasonable outlier detector. Currently `creme.stats.EWMean` is implemented but `creme.stats.EWVariance` is not. 

Would you be open to an implementation?

**Comment by MaxHalford** [comment]
For sure! I remember giving it a go but I gave up because I couldn't conciliate with results from `pandas`.

**Comment by koaning** [comment]
I'm having a similar issue, but this is a fun one to investigate. 

A few questions; 

- do we want to allow for a parameter `std=True` in the `__init__` such that this object returns standard deviation instead of merely variance? 
- can I assume that I'll never receive `NaN` values? 
- I'm having similar issues with pandas but I'll investigate that 

I thought this implementation was rather nice, @MaxHalford thoughts? 

```
class EWVar(base.Univariate):
    def __init__(self, alpha=0.5):
        self.alpha = alpha
        self.n = 0
        self.mean = EWMean(alpha=alpha)
        self.sq_mean = EWMean(alpha=alpha)

    def update(self, x):
        self.mean.update(x)
        self.sq_mean.update(x**2)
        self.n += 1
        return self

    def get(self):
        return self.sq_mean.get() - self.mean.get()**2
```

**Comment by MaxHalford** [comment]
To answer your questions:

- For the moment I would tend to say no. If we need the std in internal then we can do the square root ourselves when needed. I could be wrong though.
- Indeed, assume there are no `NaN`s. I'm not 100% sure yet but I think NaNs should be handled at a higher level.
- You never know, maybe pandas is wrong, but I doubt it ;)

Your implementation is great! However, is there any reason you need the `n` for?

**Comment by koaning** [comment]
something in pandas feels ... odd. 

![image](https://user-images.githubusercontent.com/1019791/58130783-3b29c600-7c1d-11e9-8cf7-6c3a1298ffcb.png)

**Comment by koaning** [comment]
mhm ... 

![image](https://user-images.githubusercontent.com/1019791/58130982-bee3b280-7c1d-11e9-9da9-c2fa9b6d3e88.png)

**Comment by koaning** [comment]
so when i fix the `adjust` parameter it does seem like the variance is now working. 

*... starts reading docs*

![image](https://user-images.githubusercontent.com/1019791/58131033-dd49ae00-7c1d-11e9-8dc1-c52c3d7a7f12.png)

**Comment by MaxHalford** [comment]
Yeah I'm still not clear on what exactly `adjust` does, but I don't think it matters too much. At least where the delta is coming from. Thank you so much for taking the time to do this! You can move forward :)

**Comment by MaxHalford** [comment]
Done thanks to @koaning.
