### ISSUE TITLE
Development/Testing Requirements Missing

### ISSUE THREAD

**Issue by koaning** [creme-ml/creme#95]
The package currently has all the dependencies in the `requirements.txt` file but development tools like Pytest and Sphinx are missing. Also, it seems that if I only install the current listed items that the tests fail. 

### Exibit A 

```
UNEXPECTED EXCEPTION: ModuleNotFoundError("No module named 'matplotlib'",)
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest creme.utils.histogram.Histogram[1]>", line 1, in <module>

ModuleNotFoundError: No module named 'matplotlib'
```

### Exibit B

```
  File "<doctest creme.compose.pipeline.Pipeline[11]>", line 1, in <module>

  File "/Users/vincent/Development/creme/creme/compose/pipeline.py", line 208, in draw
    raise ImportError('graphviz is not installed')

ImportError: graphviz is not installed
```

It seems like either the requirements file needs to be updated or the `setup.py` needs to be extended such that you can install dependencies via:

```
python setup.py develop
pip install -e ".[dev]"
```

There's an example in scikit lego's `setup.py` that demonstrates how you can define both development requirements as well as package requirements.

**Comment by MaxHalford** [comment]
At the moment the test dependencies are listed in the `travis.yml` file. I'll get this fixed :)

**Comment by MaxHalford** [comment]
Just pushed a fix and adjusted `CONTRIBUTING.md` accordingly. Thanks for pointing this pain point out.
